document.documentElement.classList.add('auth-lock');
const SUPA_URL='https://zicapopwsssopyxphhpo.supabase.co',SUPA_KEY='sb_publishable_qTdHbhuI7OHKofDeNcyvKg_7tFDSBs7';let sb=null,onlineMember=null;const K='scum404_v34';const base={profile:{nick:'k1t0',role:'Rifler',access:'admin'},presence:{status:'Буду',time:'20:00'},tasks:[{id:1,title:'Собрать металл',need:200,done:80,unit:'шт.',place:'Основная база',priority:'Высокий',deadline:'до сбора 21:00',owner:'k1t0',comment:'Складывать в ящик возле верстака',status:'Открыта',creator:'k1t0',history:[{nick:'k1t0',qty:30}]}],ops:[],members:[['k1t0','Rifler','20:00','Буду']]};let db=JSON.parse(localStorage.getItem(K)||'null')||base;db.ops=(db.ops||[]).map(o=>({...o,participants:Array.isArray(o.participants)?o.participants:[]}));let page='Главная';const pages=['Главная','План на вечер','Задачи','Состав','Статистика'];const $=s=>document.querySelector(s);function save(){localStorage.setItem(K,JSON.stringify(db))}function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1400)}function esc(s=''){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}function nav(){ $('#nav').innerHTML=pages.map(x=>'<button class="'+(x===page?'active':'')+'" onclick="go(\''+x+'\')">'+x+'</button>').join('')}function go(x){page=x;$('#pageTitle').textContent=x;nav();render()}function unlockApp(){document.documentElement.classList.remove('auth-lock')}function modal(html){$('#dialog').innerHTML=html;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function timePicker(name,value='20:00'){let a=(value||'20:00').split(':'),h=a[0]||'20',m=a[1]||'00';return '<div class="timepicker"><select name="'+name+'_h">'+Array.from({length:24},(_,i)=>{let v=String(i).padStart(2,'0');return '<option '+(v===h?'selected':'')+'>'+v+'</option>'}).join('')+'</select><span>:</span><select name="'+name+'_m">'+Array.from({length:12},(_,i)=>{let v=String(i*5).padStart(2,'0');return '<option '+(v===m?'selected':'')+'>'+v+'</option>'}).join('')+'</select></div>'}function getPickedTime(f,name){return f.get(name+'_h')+':'+f.get(name+'_m')}
function taskCard(t){let pct=t.need?Math.min(100,Math.round(t.done/t.need*100)):0;return '<div class="item"><div class="itemtop"><div><h3>'+esc(t.title)+'</h3><div class="muted">'+(t.need?('Нужно: '+t.need+' '+esc(t.unit)+' · Собрано: <b class="acid">'+t.done+'</b> '+esc(t.unit)):'Без количества')+(t.place?' · '+esc(t.place):'')+'</div></div><span class="badge taskstatus '+(t.status==='Выполнена'?'done':'open')+'">'+esc(t.status)+'</span></div>'+(t.need?'<div class="progress"><i style="width:'+pct+'%"></i></div><small class="muted">'+pct+'% выполнено</small>':'')+'<div class="muted" style="margin-top:8px">'+(t.owner?'Ответственный: '+esc(t.owner)+' · ':'')+esc(t.deadline||'')+'</div>'+(t.comment?'<div style="margin-top:6px">'+esc(t.comment)+'</div>':'')+'<div class="actions"><button onclick="joinTask('+t.id+')">Беру на себя</button>'+(t.need?'<button onclick="addContribution('+t.id+')">+ Добавить количество</button>':'')+'<button onclick="historyTask('+t.id+')">История</button><button onclick="toggleTask('+t.id+')">'+(t.status==='Выполнена'?'Открыть':'Выполнено')+'</button>'+(db.profile.access==='admin'?'<button class="danger" onclick="deleteTask('+t.id+')">Удалить</button>':'')+'</div></div>'}
function render(){if(page==='Сегодня')page='Главная'; $('#myNick').textContent=db.profile.nick;if(page==='Главная'||page==='Сегодня')today();if(page==='Задачи')tasks();if(page==='План на вечер'||page==='Рейд')ops();if(page==='Состав')members();if(page==='Статистика')stats()}
function today(){
 let playing=db.members.filter(x=>x[3]==='Буду').length;
 let plan=db.ops.slice(0,2).map(o=>{let p=Array.isArray(o.participants)?o.participants:[];return '<div class="item"><div class="itemtop"><h3>'+esc(o.title)+' · '+(o.date?formatPlanDate(o.date)+' · ':'')+'сбор '+esc(o.time)+'</h3><span class="badge">'+p.length+' чел.</span></div><div class="muted">'+esc(o.note||'')+'</div><div style="margin-top:10px"><small class="muted">УЧАСТНИКИ ПЛАНА</small><div class="presence" style="margin-top:6px">'+(p.length?p.map(n=>'<span class="badge work">'+esc(n)+'</span>').join(' '):'<span class="muted">Пока никто не записался</span>')+'</div></div><div class="actions"><button onclick="toggleRaid('+o.id+')">'+(p.includes(db.profile.nick)?'Не участвую':'Участвую')+'</button><button onclick="editOp('+o.id+')">Редактировать</button><button onclick="deleteOp('+o.id+')">Удалить</button></div></div>'}).join('');
 let choices=['Буду','Под вопросом','Не буду'].map(x=>'<button class="presencechoice '+(x==='Буду'?'yes':x==='Под вопросом'?'maybe':'no')+' '+(db.presence.status===x?'active':'')+'" onclick="setPresence(\''+x+'\')">'+x+'</button>').join('');
 let joinTime=db.presence.status==='Буду'?'<div style="margin-top:12px">Время захода: <b class="acid">'+esc(db.presence.time||'')+'</b> <button class="ghost" onclick="setTime()">Изменить</button></div>':'';
 let nearest=db.ops[0]?((db.ops[0].date?formatPlanDate(db.ops[0].date)+' · ':'')+db.ops[0].time):'—';
 $('#view').innerHTML='<div class="grid"><div class="card span3"><div class="muted">СЕГОДНЯ ИГРАЮТ</div><div class="metric">'+playing+'</div></div><div class="card span3"><div class="muted">ПРАЙМ</div><div class="metric">20:00-0:00</div></div><div class="card span3"><div class="muted">АКТИВНЫЕ ЗАДАЧИ</div><div class="metric">'+db.tasks.filter(t=>t.status!=="Выполнена").length+'</div></div><div class="card span3"><div class="muted">БЛИЖАЙШИЙ СБОР</div><div class="metric">'+nearest+'</div></div><div class="card span6"><div class="toolbar"><h2>План на вечер</h2><button class="primary" onclick="newOp()">+ СОЗДАТЬ ПЛАН</button></div>'+(plan||'<div class="empty">План пока не создан</div>')+'</div><div class="card span8"><div class="toolbar"><h2>Задачи</h2><button class="primary" onclick="newTask()">+ СОЗДАТЬ ЗАДАЧУ</button></div><div class="list">'+(db.tasks.filter(t=>t.status!=="Выполнена").slice(0,4).map(taskCard).join('')||'<div class="empty">Задача пока не создана</div>')+'</div></div><div class="card span6"><div class="toolbar"><h2>Моё участие</h2></div><b>'+esc(db.profile.nick)+' · '+esc(db.profile.role)+'</b><div class="presence">'+choices+'</div>'+joinTime+'</div><div class="card span4"><h2>Кто сегодня будет?</h2><div class="list">'+db.members.map(m=>'<div class="item"><div class="itemtop"><b>'+esc(m[0])+'</b><span class="badge status '+(m[3]==='Буду'?'yes':m[3]==='Под вопросом'?'maybe':'no')+'">'+esc(m[3])+'</span></div><small class="muted">'+esc(m[1])+(m[3]==='Буду'?' · '+esc(m[2]):'')+'</small></div>').join('')+'</div></div></div>';
}
function tasks(){$('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>Задачи отряда</h2><span class="muted">Собрать, налутать, скрафтить или доставить на базу.</span></div><button class="primary" onclick="newTask()">+ СОЗДАТЬ ЗАДАЧУ</button></div><div class="list">'+(db.tasks.length?db.tasks.map(taskCard).join(''):'<div class="empty">Задач пока нет</div>')+'</div></div>'}
function formatPlanDate(d){if(!d)return'';let p=d.split('-');return p.length===3?p[2]+'.'+p[1]+'.'+p[0]:d}
function ops(){$('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>План на вечер</h2><span class="muted">Создать общий план отряда на выбранную дату и время.</span></div><button class="primary" onclick="newOp()">+ СОЗДАТЬ ПЛАН</button></div><div class="list">'+(db.ops.length?db.ops.map(o=>{let p=Array.isArray(o.participants)?o.participants:[];return '<div class="item"><div class="itemtop"><div><h3>'+esc(o.title)+'</h3><div class="muted">'+(o.date?formatPlanDate(o.date)+' · ':'')+esc(o.time)+(o.note?' · '+esc(o.note):'')+'</div></div><span class="badge">'+p.length+' участников</span></div><div style="margin-top:10px"><small class="muted">УЧАСТНИКИ ПЛАНА</small><div class="presence" style="margin-top:6px">'+(p.length?p.map(n=>'<span class="badge work">'+esc(n)+'</span>').join(' '):'<span class="muted">Пока никто не записался</span>')+'</div></div><div class="actions"><button onclick="toggleRaid('+o.id+')">'+(p.includes(db.profile.nick)?'Не участвую':'Участвую')+'</button><button onclick="editOp('+o.id+')">Редактировать</button><button onclick="deleteOp('+o.id+')">Удалить</button></div></div>'}).join(''):'<div class="empty">Планов пока нет</div>')+'</div></div>'}
function members(){let admin=db.profile.access==='admin';$('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>Состав 4.0.4</h2><span class="muted">Ник, роль, время захода и статус на сегодня.</span></div>'+(admin?'<button class="ghost" onclick="changeInviteCode()">СМЕНИТЬ КОД ВСТУПЛЕНИЯ</button>':'')+'</div><div class="list">'+db.members.map(m=>'<div class="item"><div class="itemtop"><div><h3>'+esc(m[0])+(m[0]===db.profile.nick&&admin?' <span class="badge work">АДМИН</span>':'')+'</h3><span class="muted">'+esc(m[1])+'</span></div><div style="text-align:right"><b>'+(m[3]==='Буду'?esc(m[2]):'')+'</b><br><span class="badge status '+(m[3]==='Буду'?'yes':m[3]==='Под вопросом'?'maybe':'no')+'">'+esc(m[3])+'</span>'+(admin&&m[0]!==db.profile.nick?'<div style="margin-top:8px"><button class="danger" onclick="kickMemberByNick(\''+esc(m[0]).replace(/'/g,"\\'")+'\')">Выгнать</button></div>':'')+'</div></div></div>').join('')+'</div></div>'}
async function kickMemberByNick(nick){if(db.profile.access!=='admin'||!sb||!onlineMember)return;let {data:m,error:e}=await sb.from('members').select('id,nick').eq('squad_id',onlineMember.squad_id).eq('nick',nick).single();if(e||!m){toast('Участник не найден');return}if(!confirm('Выгнать '+nick+' из состава?'))return;let r=await sb.rpc('admin_kick_member',{p_member_id:m.id});if(r.error){toast('Не удалось выгнать');return}await syncOnline();toast(nick+' исключён')}
function changeInviteCode(){if(db.profile.access!=='admin')return;modal('<h2>Код вступления</h2><form class="form" onsubmit="saveInviteCode(event)"><span class="muted">Новый код для входа в состав 4.0.4</span><input name="code" required minlength="4" placeholder="Новый код"><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveInviteCode(e){e.preventDefault();let code=new FormData(e.target).get('code').trim();let r=await sb.rpc('admin_change_invite_code',{p_new_code:code});if(r.error){toast('Не удалось сменить код');return}closeModal();toast('Код вступления изменён')}
function quantityPicker(name,value=1){let opts='';for(let i=1;i<=500;i++)opts+='<option '+(i===Number(value)?'selected':'')+'>'+i+'</option>';return '<select name="'+name+'"><option value="">Количество (необязательно)</option>'+opts+'</select>'}
function newTask(){let people=(db.members||[]).map(m=>m[0]);modal('<h2>Создать задачу</h2><form class="form" onsubmit="createTask(event)"><input name="title" required placeholder="Например: Собрать металл"><div class="formrow">'+quantityPicker('need')+'<select name="unit"><option value="">Единица</option><option>Стак</option><option>Хомяк</option><option>Ящик</option></select></div><div class="formrow"><div><small class="muted">Сделать до даты</small><input name="deadline_date" class="datepick" type="date" required onclick="if(this.showPicker)this.showPicker()" onfocus="if(this.showPicker)this.showPicker()"></div><div><small class="muted">До времени</small>'+timePicker('deadline','21:00')+'</div></div><input name="place" placeholder="Куда / место"><select name="owner"><option value="">Ответственный (необязательно)</option>'+people.map(n=>'<option>'+esc(n)+'</option>').join('')+'</select><textarea name="comment" placeholder="Комментарий"></textarea><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Создать</button></div></form>')}
async function createTask(e){e.preventDefault();let f=new FormData(e.target),need=Number(f.get('need'))||null;if(!sb||!onlineMember)return;let row={squad_id:onlineMember.squad_id,creator_id:onlineMember.id,title:f.get('title'),quantity:need,unit:f.get('unit')||'шт.',place:f.get('place')||null,priority:f.get('priority')||'Обычный',deadline:(f.get('deadline_date')+' '+getPickedTime(f,'deadline')),comment:f.get('comment')||null,status:'Открыта'};let owner=String(f.get('owner')||'');if(owner){let om=(await sb.from('members').select('id').eq('squad_id',onlineMember.squad_id).eq('nick',owner).maybeSingle()).data;if(om)row.assignee_id=om.id}let {error}=await sb.from('tasks').insert(row);if(error){toast('Не удалось создать задачу');return}closeModal();await syncOnline();go('Задачи')}
async function joinTask(id){let r=await sb.rpc('claim_task',{p_task_id:id});if(r.error){toast('Не удалось взять задачу');return}await syncOnline();toast('Задача взята')}
async function addContribution(id){let q=Number(prompt('Сколько добавить?'));if(!q||q<1)return;let {error}=await sb.from('task_contributions').insert({task_id:id,member_id:onlineMember.id,amount:q});if(error){toast('Не удалось добавить вклад');return}await syncOnline();toast('Вклад добавлен')}
function historyTask(id){let t=db.tasks.find(x=>x.id===id);modal('<h2>История · '+esc(t.title)+'</h2><div class="list">'+(t.history.length?t.history.map(h=>'<div class="item itemtop"><span>'+esc(h.nick)+' · +'+h.qty+' '+esc(t.unit)+'</span><button class="ghost" onclick="undoContribution('+id+','+h.id+')">Отменить</button></div>').join(''):'<div class="empty">Вкладов пока нет</div>')+'</div><div class="dialogfoot"><button class="ghost" onclick="closeModal()">Закрыть</button></div>')}
async function undoContribution(id,cid){let {error}=await sb.from('task_contributions').delete().eq('id',cid);if(error){toast('Нельзя отменить этот вклад');return}closeModal();await syncOnline();toast('Вклад отменён')}
async function toggleTask(id){let t=db.tasks.find(x=>x.id===id),status=t.status==='Выполнена'?'Открыта':'Выполнена';let r=await sb.rpc('set_task_status',{p_task_id:id,p_status:status});if(r.error){toast('Изменить статус может ответственный, создатель или админ');return}await syncOnline()}
async function deleteTask(id){let t=db.tasks.find(x=>x.id===id);if(!t)return;if(!confirm('Удалить эту задачу?'))return;let {error}=await sb.from('tasks').delete().eq('id',id);if(error){toast('Удалить может только создатель или админ');return}await syncOnline();toast('Задача удалена')}
function newOp(){modal('<h2>План на вечер</h2><form class="form" onsubmit="createOp(event)"><input name="title" required placeholder="Название / план"><div class="formrow"><div><small class="muted">Дата</small><input name="raid_date" class="datepick" type="date" required onclick="if(this.showPicker)this.showPicker()" onfocus="if(this.showPicker)this.showPicker()"></div><div><small class="muted">Время</small>'+timePicker('time','20:00')+'</div></div><textarea name="note" placeholder="Подготовка / комментарий"></textarea><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Создать</button></div></form>')}
async function createOp(e){e.preventDefault();let f=new FormData(e.target);let {error}=await sb.from('raids').insert({squad_id:onlineMember.squad_id,creator_id:onlineMember.id,title:f.get('title'),raid_time:getPickedTime(f,'time'),raid_date:f.get('raid_date'),note:f.get('note')||null});if(error){toast('Не удалось создать план');return}closeModal();await syncOnline();render()}
function editOp(id){let o=db.ops.find(x=>x.id===id);if(!o)return;modal('<h2>Редактировать план</h2><form class="form" onsubmit="saveOp(event,'+id+')"><input name="title" required value="'+esc(o.title)+'"><div class="formrow"><div><small class="muted">Дата</small><input name="raid_date" class="datepick" type="date" required value="'+esc(o.date||'')+'" onclick="if(this.showPicker)this.showPicker()" onfocus="if(this.showPicker)this.showPicker()"></div><div><small class="muted">Время</small>'+timePicker('time',o.time||'20:00')+'</div></div><textarea name="note" placeholder="Подготовка / комментарий">'+esc(o.note)+'</textarea><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveOp(e,id){e.preventDefault();let f=new FormData(e.target);let {error}=await sb.from('raids').update({title:f.get('title'),raid_date:f.get('raid_date'),raid_time:getPickedTime(f,'time'),note:f.get('note')||null}).eq('id',id);if(error){toast('Редактировать может создатель или админ');return}closeModal();await syncOnline();toast('Рейд обновлён')}
async function deleteOp(id){if(!confirm('Удалить этот рейд?'))return;let {error}=await sb.from('raids').delete().eq('id',id);if(error){toast('Удалить может создатель или админ');return}await syncOnline();toast('Рейд удалён')}
async function toggleRaid(id){let o=db.ops.find(x=>x.id===id),joined=(o.participants||[]).includes(db.profile.nick);let q=joined?sb.from('raid_participants').delete().eq('raid_id',id).eq('member_id',onlineMember.id):sb.from('raid_participants').insert({raid_id:id,member_id:onlineMember.id});let {error}=await q;if(error){toast('Не удалось изменить участие');return}await syncOnline();toast(joined?'Ты вышел из рейда':'Ты записался на рейд')}
function raidPeople(o){let p=Array.isArray(o.participants)?o.participants:[];return p.length?p.map(n=>'<span class="badge work">'+esc(n)+'</span>').join(' '):'<span class="muted">Пока никто не записался</span>'}
async function setPresence(s){if(s==='Без меня')s='Не буду';let old={...db.presence};db.presence.status=s;if(s!=='Буду')db.presence.time='';save();render();let row={squad_id:onlineMember.squad_id,member_id:onlineMember.id,day:moscowPresenceDay(),status:s,join_time:s==='Буду'?(db.presence.time||null):null,updated_at:new Date().toISOString()};let {error}=await sb.from('presence_history').upsert(row,{onConflict:'member_id,day'});if(error){db.presence=old;save();render();toast('Ошибка синхронизации');return}await syncOnline();if(s==='Буду')setTime()}function setTime(){modal('<h2>Время захода</h2><form class="form" onsubmit="saveTime(event)"><label class="muted">Выбери время</label>'+timePicker('time',db.presence.time||'20:00')+'<div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}async function saveTime(e){e.preventDefault();let f=new FormData(e.target),t=getPickedTime(f,'time');db.presence.time=t;let status=db.presence.status==='Не буду'?'Буду':db.presence.status;let row={squad_id:onlineMember.squad_id,member_id:onlineMember.id,day:moscowPresenceDay(),status,join_time:t,updated_at:new Date().toISOString()};let {error}=await sb.from('presence_history').upsert(row,{onConflict:'member_id,day'});if(error){toast('Ошибка синхронизации');return}closeModal();await syncOnline();toast('Время обновлено')}
function editProfile(){let admin=db.profile.access==='admin';modal('<h2>Профиль бойца</h2>'+(admin?'<div style="margin-bottom:12px"><span class="badge work">АДМИНИСТРАТОР 4.0.4</span></div>':'')+'<form class="form" onsubmit="saveProfile(event)"><input name="nick" required value="'+esc(db.profile.nick)+'" placeholder="Ник"><select name="role">'+['Rifler','Bomber','Locker','Builder','Helper','Sniper'].map(r=>'<option '+(r===db.profile.role?'selected':'')+'>'+r+'</option>').join('')+'</select><div class="dialogfoot"><button type="button" class="logoutbtn" onclick="logoutSquad()">ВЫЙТИ</button><span style="flex:1"></span><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveProfile(e){e.preventDefault();let f=new FormData(e.target);let {error}=await sb.from('members').update({nick:f.get('nick'),game_role:f.get('role')}).eq('id',onlineMember.id);if(error){toast('Не удалось сохранить профиль');return}onlineMember.nick=f.get('nick');onlineMember.game_role=f.get('role');db.profile={nick:onlineMember.nick,role:onlineMember.game_role,access:onlineMember.access_role};save();closeModal();await syncOnline();toast('Профиль сохранён')}
async function logoutSquad(){if(!confirm('Выйти из профиля на этом устройстве?'))return;if(sb)await sb.auth.signOut();onlineMember=null;localStorage.removeItem(K);db=JSON.parse(JSON.stringify(base));closeModal();render();document.documentElement.classList.add('auth-lock');toast('Вы вышли');setTimeout(()=>joinOnline(),300)}
function stats(){let periods=[1,7,14,30],sel=window.statDays||7;$('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>Статистика состава</h2><span class="muted">Выбери период. Активный период выделен зелёным.</span></div><div class="presence statperiods">'+periods.map(n=>'<button type="button" class="'+(sel===n?'on':'')+'" data-days="'+n+'">'+(n===1?'День':n+' дней')+'</button>').join('')+'</div></div><div id="statPeriodLabel" class="statperiodlabel">Показан период: <b>'+(sel===1?'сегодня':sel+' дней')+'</b></div><div id="statsBody"><div class="empty">Загрузка…</div></div></div>';document.querySelectorAll('.statperiods button').forEach(btn=>btn.addEventListener('click',()=>{let n=Number(btn.dataset.days);window.statDays=n;document.querySelectorAll('.statperiods button').forEach(x=>x.classList.toggle('on',x===btn));let l=$('#statPeriodLabel');if(l)l.innerHTML='Показан период: <b>'+(n===1?'сегодня':n+' дней')+'</b>';loadStats(n)}));loadStats(sel)}
async function loadStats(days){window.statDays=days;if(page!=='Статистика'){go('Статистика');return}let b=$('#statsBody');if(!sb||!onlineMember){b.innerHTML='<div class="empty">Войди в состав, чтобы видеть статистику</div>';return}let from=new Date();from.setDate(from.getDate()-days+1);let {data,error}=await sb.from('presence_history').select('day,status,join_time,member_id,members!inner(nick)').gte('day',from.toISOString().slice(0,10)).order('day',{ascending:false});if(error){b.innerHTML='<div class="empty">Не удалось загрузить статистику</div>';return}window.statsRows=data||[];let by={};window.statsRows.forEach(x=>{let n=x.members.nick;(by[n]||(by[n]=[])).push(x)});b.innerHTML=Object.keys(by).length?Object.entries(by).map(([n,rows])=>'<div class="item"><h3>'+esc(n)+'</h3>'+['Буду','Под вопросом','Не буду'].map(s=>{let a=rows.filter(x=>x.status===s);return '<div style="margin-top:9px"><span class="badge status '+(s==='Буду'?'yes':s==='Под вопросом'?'maybe':'no')+'">'+s+' · '+a.length+'</span> <span class="muted">'+(a.length?a.map(x=>'<button class="statdate" onclick="showStatDay(\''+x.day+'\')">'+new Date(x.day+'T00:00:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'})+'</button>').join(' '):'—')+'</span></div>'}).join('')+'</div>').join(''):'<div class="empty">За этот период отметок пока нет</div>'}
function showStatDay(day){let rows=(window.statsRows||[]).filter(x=>x.day===day);let title=new Date(day+'T00:00:00').toLocaleDateString('ru-RU',{day:'2-digit',month:'long',year:'numeric'});modal('<h2>'+title+'</h2><div class="list">'+(rows.length?rows.map(x=>'<div class="item itemtop"><div><b>'+esc(x.members.nick)+'</b>'+(x.status==='Буду'&&x.join_time?'<div class="muted" style="margin-top:4px">Заход: '+esc(x.join_time.slice(0,5))+'</div>':'')+'</div><span class="badge status '+(x.status==='Буду'?'yes':x.status==='Под вопросом'?'maybe':'no')+'">'+esc(x.status)+'</span></div>').join(''):'<div class="empty">Нет отметок</div>')+'</div><div class="dialogfoot"><button class="ghost" onclick="closeModal()">Закрыть</button></div>')}
function authScreen(){modal('<h2>Вход в 4.0.4</h2><div class="presence" style="margin-bottom:16px"><button class="on" id="memberTab" onclick="showMemberLogin()">УЧАСТНИК</button><button id="adminTab" onclick="showAdminLogin()">АДМИН</button></div><div id="authForm"></div>');showMemberLogin()}
function showMemberLogin(){let a=$('#authForm');if(!a)return;$('#memberTab')?.classList.add('on');$('#adminTab')?.classList.remove('on');a.innerHTML='<form class="form" onsubmit="doJoin(event)"><input name="code" required placeholder="Код состава"><input name="nick" required value="'+esc(db.profile.nick)+'" placeholder="Ник"><select name="role">'+['Rifler','Bomber','Locker','Builder','Helper','Sniper'].map(r=>'<option>'+r+'</option>').join('')+'</select><button class="primary">ВОЙТИ В СОСТАВ</button></form>'}
function showAdminLogin(){let a=$('#authForm');if(!a)return;$('#adminTab')?.classList.add('on');$('#memberTab')?.classList.remove('on');a.innerHTML='<form class="form" onsubmit="adminLogin(event)"><input name="email" type="email" required autocomplete="username" placeholder="E-mail"><input name="password" type="password" required minlength="6" autocomplete="current-password" placeholder="Пароль"><button class="primary">ВОЙТИ КАК АДМИН</button><button type="button" class="ghost" onclick="adminSignup(event)">ПЕРВЫЙ ВХОД / СОЗДАТЬ ПАРОЛЬ</button><div id="adminAuthStatus" class="muted" style="min-height:18px"></div></form><small class="muted">При первом входе создай пароль. После этого используй обычный вход администратора.</small>'}
async function adminSignup(e){if(e)e.preventDefault();let st=$('#adminAuthStatus'),form=$('#authForm form');if(!form)return;let f=new FormData(form),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');if(!email){if(st)st.textContent='Введи e-mail';return}if(password.length<6){if(st)st.textContent='Пароль минимум 6 символов';return}if(st)st.textContent='Создаю учётную запись…';let r=await sb.auth.signUp({email,password});if(r.error){if(st)st.textContent='Ошибка: '+r.error.message;return}if(!r.data.session){if(st)st.textContent='Готово. Проверь почту и подтверди e-mail, затем нажми «ВОЙТИ КАК АДМИН».';return}if(st)st.textContent='Учётная запись создана. Вхожу…';await finishAdminLogin()}
async function adminLogin(e){e.preventDefault();let f=new FormData(e.target);await sb.auth.signOut();let r=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(r.error){toast('Неверный e-mail или пароль');return}await finishAdminLogin()}
async function finishAdminLogin(){let r=await sb.rpc('claim_admin_account');if(r.error){toast('Эта учётка не является администратором');await sb.auth.signOut();return}onlineMember=r.data;db.profile={nick:r.data.nick,role:r.data.game_role,access:r.data.access_role};save();closeModal();await syncOnline();unlockApp();toast('Вход администратора выполнен')}
async function joinOnline(){if(!sb)return;let {data:{session}}=await sb.auth.getSession();if(session){let {data:m}=await sb.from('members').select('*').eq('user_id',session.user.id).maybeSingle();if(m){onlineMember=m;db.profile={nick:m.nick,role:m.game_role,access:m.access_role};save();await syncOnline();unlockApp();return}if(!session.user.is_anonymous&&session.user.email?.toLowerCase()==='nikitinrf@bk.ru'){await finishAdminLogin();return}}authScreen()}
async function ensureAnonymous(){let {data:{session}}=await sb.auth.getSession();if(!session||!session.user.is_anonymous){if(session)await sb.auth.signOut();let r=await sb.auth.signInAnonymously();if(r.error)throw r.error}}
async function doJoin(e){e.preventDefault();let f=new FormData(e.target);try{await ensureAnonymous()}catch(x){toast('Не удалось создать сессию');return}let {data,error}=await sb.rpc('join_squad',{p_code:f.get('code'),p_nick:f.get('nick'),p_role:f.get('role')});if(error){toast(error.message.includes('duplicate')?'Ник уже занят':'Неверный код или ошибка входа');return}onlineMember=data;db.profile={nick:data.nick,role:data.game_role,access:data.access_role};save();closeModal();await syncOnline();unlockApp();toast('Добро пожаловать в 4.0.4')}
let syncTimer=null;function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{if(onlineMember&&document.visibilityState==='visible')syncOnline()},350)}
function startSharedSync(){if(window.sharedSyncStarted)return;window.sharedSyncStarted=true;setInterval(()=>{if(onlineMember&&document.visibilityState==='visible')syncOnline()},10000);try{sb.channel('squad-shared').on('postgres_changes',{event:'*',schema:'public'},scheduleSync).subscribe()}catch(e){console.warn(e)}}
function moscowPresenceDay(){let parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let v=Object.fromEntries(parts.map(x=>[x.type,x.value]));let d=new Date(Date.UTC(+v.year,+v.month-1,+v.day));if(+v.hour<5)d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)}
async function syncOnline(){if(!sb||!onlineMember)return;let day=moscowPresenceDay();let [mr,pr,tr,cr,rr,rpr]=await Promise.all([
sb.from('members').select('*').order('joined_at'),
sb.from('presence_history').select('*').eq('day',day),
sb.from('tasks').select('*').eq('squad_id',onlineMember.squad_id).order('created_at',{ascending:false}),
sb.from('task_contributions').select('*').order('created_at'),
sb.from('raids').select('*').eq('squad_id',onlineMember.squad_id).order('created_at',{ascending:false}),
sb.from('raid_participants').select('*')
]);if(mr.error||pr.error||tr.error||cr.error||rr.error||rpr.error){toast('Ошибка синхронизации');return}let ms=mr.data||[],ph=pr.data||[],nameById=Object.fromEntries(ms.map(m=>[m.id,m.nick]));db.members=ms.map(m=>{let p=ph.find(x=>x.member_id===m.id);return[m.nick,m.game_role,p?.join_time?.slice(0,5)||'',p?.status||'Не буду']});db.tasks=(tr.data||[]).map(t=>{let hs=(cr.data||[]).filter(c=>c.task_id===t.id).map(c=>({id:c.id,nick:nameById[c.member_id]||'Боец',qty:c.amount}));let done=hs.reduce((n,h)=>n+h.qty,0);return{id:t.id,title:t.title,need:t.quantity||0,done,unit:t.unit||'шт.',place:t.place||'',priority:t.priority,deadline:t.deadline||'',owner:nameById[t.assignee_id]||'',comment:t.comment||'',status:t.status,creator:nameById[t.creator_id]||'',history:hs}});db.ops=(rr.data||[]).map(r=>({id:r.id,title:r.title,date:r.raid_date||'',time:r.raid_time?.slice(0,5)||'20:00',note:r.note||'',creator:nameById[r.creator_id]||'',participants:(rpr.data||[]).filter(x=>x.raid_id===r.id).map(x=>nameById[x.member_id]).filter(Boolean)})).sort((a,b)=>{let av=a.date?(a.date+'T'+(a.time||'00:00')):'9999-12-31T23:59',bv=b.date?(b.date+'T'+(b.time||'00:00')):'9999-12-31T23:59';return av.localeCompare(bv)});let me=ms.find(x=>x.id===onlineMember.id);if(me){onlineMember=me;db.profile={nick:me.nick,role:me.game_role,access:me.access_role}}let p=ph.find(x=>x.member_id===onlineMember.id);db.presence=p?{status:p.status,time:p.join_time?.slice(0,5)||''}:{status:'Не буду',time:''};save();render();startSharedSync()}
async function bootOnline(){try{sb=supabase.createClient(SUPA_URL,SUPA_KEY);await joinOnline()}catch(e){console.error(e);toast('Supabase недоступен')}}
nav();render();bootOnline();