document.documentElement.classList.add('auth-lock');
const SUPA_URL='https://zicapopwsssopyxphhpo.supabase.co',SUPA_KEY='sb_publishable_qTdHbhuI7OHKofDeNcyvKg_7tFDSBs7';let sb=null,onlineMember=null;const K='scumfury_v34';const base={profile:{nick:'k1t0',role:'Rifler',access:'admin'},presence:{status:'Буду',time:'20:00'},tasks:[{id:1,title:'Собрать металл',need:200,done:80,unit:'шт.',place:'Основная база',priority:'Высокий',deadline:'до сбора 21:00',owner:'k1t0',comment:'Складывать в ящик возле верстака',status:'В процессе',creator:'k1t0',history:[{nick:'k1t0',qty:30}]}],ops:[],members:[['k1t0','Rifler','20:00','Буду']]};let db=JSON.parse(localStorage.getItem(K)||'null')||base;db.ops=(db.ops||[]).map(o=>({...o,participants:Array.isArray(o.participants)?o.participants:[]}));const pages=['Главная','План на рейд','Задачи','Взрыв','Схрон','Базы','Состав'];let page=localStorage.getItem('fury_active_page')||'Главная';if(!pages.includes(page))page='Главная';const $=s=>document.querySelector(s);function save(){localStorage.setItem(K,JSON.stringify(db))}function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),1400)}function esc(s=''){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}function nav(){ $('#nav').innerHTML=pages.map(x=>'<button class="'+(x===page?'active':'')+'" onclick="go(\''+x+'\')">'+x+'</button>').join('')}function toggleMobileNav(){document.querySelector('aside')?.classList.toggle('mobile-nav-open')}function go(x){page=x;localStorage.setItem('fury_active_page',x);$('#pageTitle').textContent=x;document.querySelector('aside')?.classList.remove('mobile-nav-open');nav();render()}function unlockApp(){document.documentElement.classList.remove('auth-lock')}function modal(html){$('#dialog').innerHTML=html;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
function stepWalls(btn,delta){let box=btn.closest('.wallpicker'),input=box.querySelector('input'),n=Math.max(0,(parseInt(input.value,10)||0)+delta);input.value=n}
function timePicker(name,value='20:00'){let a=(value||'20:00').split(':'),h=a[0]||'20',m=a[1]||'00';return '<div class="timepicker"><div class="timefield"><span>'+h+'</span><select name="'+name+'_h" onchange="this.previousElementSibling.textContent=this.value">'+Array.from({length:24},(_,i)=>{let v=String(i).padStart(2,'0');return '<option '+(v===h?'selected':'')+'>'+v+'</option>'}).join('')+'</select></div><b>:</b><div class="timefield"><span>'+m+'</span><select name="'+name+'_m" onchange="this.previousElementSibling.textContent=this.value">'+Array.from({length:60},(_,i)=>{let v=String(i).padStart(2,'0');return '<option '+(v===m?'selected':'')+'>'+v+'</option>'}).join('')+'</select></div></div>'}function getPickedTime(f,name){return f.get(name+'_h')+':'+f.get(name+'_m')}
function unitForm(n,u){n=Number(n)||0;u=String(u||'шт.');let m=n%100,a=n%10;if(u==='Хомяк')return (m>=11&&m<=14)?'хомяков':a===1?'хомяк':(a>=2&&a<=4)?'хомяка':'хомяков';if(u==='Ящик')return (m>=11&&m<=14)?'ящиков':a===1?'ящик':(a>=2&&a<=4)?'ящика':'ящиков';if(u==='Стак')return (m>=11&&m<=14)?'стаков':a===1?'стак':(a>=2&&a<=4)?'стака':'стаков';return u}
function taskCard(t){let pct=t.need?Math.min(100,Math.round(t.done/t.need*100)):0,people=[...new Set((t.history||[]).map(x=>x.nick))];return '<div class="item taskclick" onclick="taskDetails('+t.id+',event)"><div class="itemtop"><div><h3>'+esc(t.title)+'</h3><div class="muted">'+(t.need?('Нужно: '+t.need+' '+unitForm(t.need,t.unit)+' · Собрано: <b class="acid">'+t.done+'</b> '+unitForm(t.done,t.unit)):'Без количества')+(t.place?' · '+esc(t.place):'')+'</div></div><span class="badge taskstatus '+(t.status==='Выполнено'||t.status==='Выполнена'?'done':'open')+'">'+esc(t.status==='Открыта'?'В процессе':t.status)+'</span></div>'+(t.need?'<div class="progress"><i style="width:'+pct+'%"></i></div><small class="muted">'+pct+'% выполнено</small>':'')+'<div class="muted" style="margin-top:8px">'+(t.deadline?('До: '+esc(t.deadline)):'')+'</div>'+(people.length?'<div style="margin-top:8px"><small class="muted">Участники:</small><div class="presence" style="margin-top:6px">'+people.map(n=>'<span class="badge work">'+esc(n)+'</span>').join(' ')+'</div></div>':'')+(t.comment?'<div style="margin-top:6px">'+esc(t.comment)+'</div>':'')+'<div class="actions">'+(t.need?'<button onclick="event.stopPropagation();addContribution('+t.id+')">+ Добавить количество</button>':'')+((t.creator===db.profile.nick||db.profile.access==='admin')?'<button onclick="event.stopPropagation();editTask('+t.id+')">Редактировать</button>':'')+(db.profile.access==='admin'?'<button class="danger" onclick="event.stopPropagation();deleteTask('+t.id+')">Удалить</button>':'')+'</div></div>'}
function showTaskComplete(){let d=document.createElement('div');d.className='task-complete-flash';d.textContent='ВЫПОЛНЕНО';document.body.appendChild(d);requestAnimationFrame(()=>d.classList.add('show'));setTimeout(()=>{d.classList.remove('show');setTimeout(()=>d.remove(),250)},1800)}
function taskDetails(id,e){if(e&&e.target.closest('button'))return;let t=db.tasks.find(x=>x.id===id);if(!t)return;let hist=t.history||[];modal('<h2>'+esc(t.title)+'</h2><div class="muted">'+(t.need?('Нужно: '+t.need+' '+unitForm(t.need,t.unit)+' · Собрано: '+t.done+' '+unitForm(t.done,t.unit)):'Без количества')+'</div>'+(t.place?'<p>Место: '+esc(t.place)+'</p>':'')+(t.deadline?'<p>До: '+esc(t.deadline)+'</p>':'')+(t.comment?'<p>'+esc(t.comment)+'</p>':'')+'<h3 style="margin-top:20px">История</h3><div class="list">'+(hist.length?hist.map(h=>'<div class="item itemtop"><span>'+esc(h.nick)+' · +'+h.qty+' '+unitForm(h.qty,t.unit)+'</span><button class="ghost" onclick="undoContribution('+id+','+h.id+')">Отменить</button></div>').join(''):'<div class="empty">Вкладов пока нет</div>')+'</div><div class="dialogfoot"><button class="ghost" onclick="closeModal()">Закрыть</button></div>')}
function render(){if(page==='Сегодня')page='Главная'; $('#myNick').textContent=db.profile.nick;let sc=$('#squadCount');if(sc){let n=db.members.length;sc.textContent=n+' '+(n%10===1&&n%100!==11?'УЧАСТНИК':(n%10>=2&&n%10<=4&&(n%100<12||n%100>14)?'УЧАСТНИКА':'УЧАСТНИКОВ'));}if(page==='Главная'||page==='Сегодня')today();if(page==='Задачи')tasks();if(page==='План на рейд'||page==='Рейд')ops();if(page==='Состав')members();if(page==='Взрыв')stats();if(page==='Схрон')placePage('stash');if(page==='Базы')placePage('base')}
function today(){
 let playing=db.members.filter(x=>x[3]==='Буду').length,walls=Number(window.furyWalls||0),activeTasks=db.tasks.filter(t=>t.status!=='Выполнено'&&t.status!=='Выполнена');
 let plan=db.ops.slice(0,3).map(o=>{let p=Array.isArray(o.participants)?o.participants:[];return '<div class="ref-plan-row raidclick" onclick="viewOp('+o.id+')"><span class="ref-dot"></span><b class="ref-time">'+esc(o.time)+'</b><div class="ref-plan-name"><b>'+esc(o.title)+'</b><small>'+esc(o.note||'')+'</small></div><div class="ref-people">'+(p.slice(0,3).map(n=>'<i>'+esc(n).slice(0,1).toUpperCase()+'</i>').join(''))+(p.length>3?'<em>+'+(p.length-3)+'</em>':'')+'</div></div>'}).join('');
 let taskRows=activeTasks.slice(0,5).map(t=>'<div class="ref-task-row" onclick="taskDetails('+t.id+',event)"><span class="ref-ring"></span><b>'+esc(t.title)+'</b><span>'+Number(t.done||0)+' / '+Number(t.need||0)+'</span></div>').join('');
 let choices=['Буду','Под вопросом','Не буду'].map(x=>'<button class="presencechoice '+(x==='Буду'?'yes':x==='Под вопросом'?'maybe':'no')+' '+(db.presence.status===x?'active':'')+'" onclick="setPresence(\''+x+'\')">'+x+'</button>').join('');
 let protectText=db.protect?protectHomeHtml(db.protect):'—';
 refreshWallMetric();
 $('#view').innerHTML='<div class="ref-home">'+
 '<div class="ref-top">'+
  '<section class="ref-card ref-plan"><div class="ref-title"><span class="ref-icon green">▣</span><h2>ПЛАН НА ВЕЧЕР</h2><b>'+db.ops.length+'</b></div><div class="ref-list">'+(plan||'<div class="empty">План пока не создан</div>')+'</div></section>'+
  '<section class="ref-card ref-tasks"><div class="ref-title"><span class="ref-icon red">◎</span><h2>АКТИВНЫЕ ЗАДАЧИ</h2><b>'+activeTasks.length+'</b></div><div class="ref-list">'+(taskRows||'<div class="empty">Задач пока нет</div>')+'</div></section>'+
 '</div>'+
 '<div class="ref-middle">'+
  '<section class="ref-card ref-att"><div class="ref-title"><span class="ref-icon green">♙</span><h2>МОЁ УЧАСТИЕ</h2></div><div class="ref-mini-stats"><div><small>ЗАПЛАНИРОВАНО</small><b>'+db.tasks.length+' '+(db.tasks.length===1?'задача':'задачи')+'</b></div><div><small>УЧАСТВУЮ</small><b>'+db.ops.filter(o=>(o.participants||[]).includes(db.profile.nick)).length+' рейда</b></div><div><small>ВЫПОЛНЕНО</small><b>'+db.tasks.filter(t=>t.status==='Выполнено'||t.status==='Выполнена').length+' задача</b></div></div><div class="ref-att-head"><h3>КТО СЕГОДНЯ БУДЕТ?</h3><b>'+playing+' / '+db.members.length+'</b></div><div class="ref-members">'+db.members.map(m=>'<div class="ref-member"><div class="ref-avatar">'+esc(m[0]).slice(0,1).toUpperCase()+'</div><b>'+esc(m[0])+'</b><div class="ref-statuses">'+(m[0]===db.profile.nick?choices:'<span class="ref-status '+(m[3]==='Буду'?'yes':m[3]==='Под вопросом'?'maybe':'no')+'">'+esc(m[3])+'</span>')+'</div><span class="ref-member-time">'+(m[3]==='Буду'?esc(m[2]||'20:00–00:00'):'—')+'</span></div>').join('')+'</div></section>'+
  '<section class="ref-card ref-feed"><div class="ref-title"><span class="ref-icon">▣</span><h2>ФОТО И КОММЕНТАРИИ</h2><button class="ghost" onclick="homeFeedAll=true;homeFeedShown=15;renderHomePlace()">Все записи</button></div><div id="homePlaceBody"><div class="empty">Загрузка…</div></div></section>'+
 '</div>'+
 '<section class="ref-card ref-expl"><div class="ref-title"><span class="ref-icon red">✣</span><h2>ВЗРЫВ</h2><small>Общий склад отряда. Любой участник может изменить количество.</small><button class="ghost" onclick="go(\'Взрыв\')">Открыть</button></div><div id="refExplosiveStrip"><div class="empty">Загрузка склада…</div></div></section>'+
 '</div>'; renderHomePlace(); renderRefExplosives();
}
function renderRefExplosives(){
 let host=document.getElementById('refExplosiveStrip');if(!host)return;
 let inv=(db.explosives||window.explosives||[]),names=['С4','РПГ','ГРАНАТА','ДИНАМИТ','ПАЙПА','40'];
 let getQ=n=>{let x=inv.find(v=>String(v.item||v.name||'').toUpperCase()===n);return Number(x?.qty??x?.quantity??0)};
 let per={'С4':3,'РПГ':6,'ГРАНАТА':12,'ДИНАМИТ':6};
 let cards=names.map(n=>{let q=getQ(n),pw=per[n],w=pw?Math.floor(q/pw):0,r=pw?q%pw:0;return '<div class="ref-expl-item"><div class="ref-expl-pic">'+(n==='С4'?'▰':n==='РПГ'?'╱':n==='ГРАНАТА'?'●':n==='ДИНАМИТ'?'▥':n==='ПАЙПА'?'╱':'◆')+'</div><div><b>'+n+'</b><strong>'+q+'</strong><small>В наличии · '+w+' стен'+(r?' + '+r+' '+n:'')+'</small></div></div>'}).join('');
 host.innerHTML='<div class="ref-expl-items">'+cards+'</div><div class="ref-wall-total"><small>МОЖНО ВЗОРВАТЬ</small><b>'+Number(window.furyWalls||0)+' СТЕН</b></div>';
}
function tasks(){$('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>Задачи отряда</h2><span class="muted">Собрать, налутать, скрафтить или доставить на базу.</span></div><button class="primary" onclick="newTask()">+ СОЗДАТЬ ЗАДАЧУ</button></div><div class="list">'+(db.tasks.length?db.tasks.map(taskCard).join(''):'<div class="empty">Задач пока нет</div>')+'</div></div>'}
function participantWord(n){n=Number(n)||0;let m=n%100,a=n%10;return (m>=11&&m<=14)?'участников':a===1?'участник':(a>=2&&a<=4)?'участника':'участников'}
function formatPlanDate(d){if(!d)return'';let p=d.split('-');return p.length===3?p[2]+'.'+p[1]+'.'+p[0]:d}
function ops(){$('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>План на рейд</h2><span class="muted">Создать общий план отряда на выбранную дату и время.</span></div><button class="primary" onclick="newOp()">+ СОЗДАТЬ ПЛАН</button></div><div class="list">'+(db.ops.length?db.ops.map(o=>{let p=Array.isArray(o.participants)?o.participants:[];return '<div class="item raiditem raidclick" onclick="viewOp('+o.id+')"><div class="itemtop"><div style="flex:1"><h3>'+esc(o.title)+'</h3><div class="muted">'+(o.date?formatPlanDate(o.date)+' · ':'')+esc(o.time)+(o.note?' · '+esc(o.note):'')+'</div></div><span class="badge">'+p.length+' '+participantWord(p.length)+'</span></div><div style="margin-top:10px"><small class="muted">Участники:</small><div class="presence" style="margin-top:6px">'+(p.length?p.map(n=>'<span class="badge work">'+esc(n)+'</span>').join(' '):'<span class="muted">Пока никто не записался</span>')+'</div></div><div class="actions"><button onclick="event.stopPropagation();toggleRaid('+o.id+')">'+(p.includes(db.profile.nick)?'Не участвую':'Участвую')+'</button><button onclick="event.stopPropagation();editOp('+o.id+')">Редактировать</button><button onclick="event.stopPropagation();deleteOp('+o.id+')">Удалить</button></div></div>'}).join(''):'<div class="empty">Планов пока нет</div>')+'</div></div>'}
let photoScrollY=0;
function closeRaidPhoto(){
 const d=document.getElementById('photoViewer');if(d)d.remove();
 document.documentElement.style.overflow='';
 document.body.style.overflow='';
 document.body.style.position='';
 document.body.style.top='';
 document.body.style.width='';
 window.scrollTo(0,photoScrollY);
}
function openRaidPhoto(url){
 closeRaidPhoto();
 photoScrollY=window.scrollY||window.pageYOffset||0;
 document.documentElement.style.overflow='hidden';
 document.body.style.overflow='hidden';
 document.body.style.position='fixed';
 document.body.style.top='-'+photoScrollY+'px';
 document.body.style.width='100%';

 const d=document.createElement('div');
 d.id='photoViewer';
 d.setAttribute('style','position:fixed!important;inset:0!important;z-index:2147483647!important;background:#000!important;overflow:hidden!important;overscroll-behavior:none!important;margin:0!important;padding:0!important;box-sizing:border-box!important;');

 const img=document.createElement('img');
 img.src=url;img.alt='Фото';img.onclick=closeRaidPhoto;
 img.setAttribute('style','position:absolute!important;display:block!important;margin:0!important;padding:0!important;border:0!important;border-radius:0!important;max-width:none!important;max-height:none!important;min-width:0!important;min-height:0!important;object-fit:fill!important;object-position:center!important;transform:none!important;');
 d.appendChild(img);document.body.appendChild(d);

 const fit=()=>{
   if(!img.naturalWidth||!img.naturalHeight)return;
   const vv=window.visualViewport;
   const vw=Math.max(1,Math.floor(vv?.width||window.innerWidth));
   const vh=Math.max(1,Math.floor(vv?.height||window.innerHeight));
   const pad=16,aw=Math.max(1,vw-pad*2),ah=Math.max(1,vh-pad*2);
   const scale=Math.min(aw/img.naturalWidth,ah/img.naturalHeight);
   const w=Math.floor(img.naturalWidth*scale),hh=Math.floor(img.naturalHeight*scale);
   d.style.width=vw+'px';d.style.height=vh+'px';
   img.style.setProperty('width',w+'px','important');
   img.style.setProperty('height',hh+'px','important');
   img.style.setProperty('left',Math.floor((vw-w)/2)+'px','important');
   img.style.setProperty('top',Math.floor((vh-hh)/2)+'px','important');
 };
 img.onload=()=>requestAnimationFrame(fit);
 fit();
 if(window.visualViewport)window.visualViewport.addEventListener('resize',fit,{once:true});
 d.addEventListener('click',e=>{if(e.target===d)closeRaidPhoto()});
}
function viewOp(id){let o=db.ops.find(x=>x.id===id);if(!o)return;modal('<h2>'+esc(o.title)+'</h2><p>'+(o.date?formatPlanDate(o.date)+' · ':'')+esc(o.time)+'</p>'+(o.sector?'<p>Сектор: '+esc(o.sector)+'</p>':'')+(o.walls?'<p>Стены: '+o.walls+'</p>':'')+(o.transport?'<p>Транспорт: '+esc(o.transport)+'</p>':'')+(o.loadout?'<p>Что взять: '+esc(o.loadout)+'</p>':'')+(o.rally_point?'<p>Точка сбора: '+esc(o.rally_point)+'</p>':'')+(o.note?'<p>Комментарий: '+esc(o.note)+'</p>':'')+(o.images&&o.images.length?'<div class="raidphotos">'+o.images.map(u=>'<img src="'+esc(u)+'" alt="Фото для рейда" onclick="openRaidPhoto(\''+esc(u)+'\')" style="cursor:zoom-in">').join('')+'</div>':'')+'<div class="dialogfoot"><button class="ghost" onclick="closeModal()">Закрыть</button></div>')}
function members(){let admin=db.profile.access==='admin'||db.profile.nick==='k1t0';$('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>Состав FURY</h2><span class="muted">Ник, роль, время захода и статус на сегодня.</span></div>'+(admin?'<button class="ghost" onclick="changeInviteCode()">СМЕНИТЬ КОД ВСТУПЛЕНИЯ</button>':'')+'</div><div class="list">'+db.members.map(m=>'<div class="item"><div class="itemtop"><div><h3>'+esc(m[0])+(m[0]===db.profile.nick&&admin?' <span class="badge work">АДМИН</span>':'')+'</h3><span class="muted">'+esc(m[1])+'</span></div><div style="text-align:right"><b>'+(m[3]==='Буду'?esc(m[2]):'')+'</b><br><span class="badge status '+(m[3]==='Буду'?'yes':m[3]==='Под вопросом'?'maybe':'no')+'">'+esc(m[3])+'</span>'+(admin&&m[0]!==db.profile.nick?'<div class="actions" style="justify-content:flex-end;margin-top:8px"><button onclick="editMemberNick(\''+esc(m[0]).replace(/'/g,"\\'")+'\')">Изменить ник</button><button class="danger" onclick="kickMemberByNick(\''+esc(m[0]).replace(/'/g,"\\'")+'\')">Выгнать</button></div>':'')+'</div></div></div>').join('')+'</div></div>'}
function editMemberNick(nick){if(db.profile.access!=='admin'&&db.profile.nick!=='k1t0')return;modal('<h2>Изменить ник</h2><form class="form" onsubmit="saveMemberNick(event,\''+esc(nick).replace(/'/g,"\\'")+'\')"><span class="muted">Текущий ник: '+esc(nick)+'</span><input name="nick" required maxlength="40" value="'+esc(nick)+'" placeholder="Новый ник"><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveMemberNick(e,oldNick){e.preventDefault();if(!sb||!onlineMember)return;let newNick=String(new FormData(e.target).get('nick')||'').trim();if(!newNick)return;let {data:m,error}=await sb.from('members').select('id').eq('squad_id',onlineMember.squad_id).eq('nick',oldNick).single();if(error||!m){toast('Участник не найден');return}let r=await sb.rpc('admin_rename_member',{p_member_id:m.id,p_new_nick:newNick});if(r.error){toast(r.error.message.includes('exists')?'Такой ник уже занят':'Не удалось изменить ник');return}closeModal();await syncOnline();toast('Ник изменён: '+oldNick+' → '+newNick)}

async function kickMemberByNick(nick){if(db.profile.access!=='admin'||!sb||!onlineMember)return;let {data:m,error:e}=await sb.from('members').select('id,nick').eq('squad_id',onlineMember.squad_id).eq('nick',nick).single();if(e||!m){toast('Участник не найден');return}if(!confirm('Выгнать '+nick+' из состава?'))return;let r=await sb.rpc('admin_kick_member',{p_member_id:m.id});if(r.error){toast('Не удалось выгнать');return}await syncOnline();toast(nick+' исключён')}
function changeInviteCode(){if(db.profile.access!=='admin')return;modal('<h2>Код вступления</h2><form class="form" onsubmit="saveInviteCode(event)"><span class="muted">Новый код для входа в состав FURY</span><input name="code" required minlength="4" placeholder="Новый код"><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveInviteCode(e){e.preventDefault();let code=new FormData(e.target).get('code').trim();let r=await sb.rpc('admin_change_invite_code',{p_new_code:code});if(r.error){toast('Не удалось сменить код');return}closeModal();toast('Код вступления изменён')}
function quantityPicker(name,value=1){let opts='';for(let i=1;i<=500;i++)opts+='<option '+(i===Number(value)?'selected':'')+'>'+i+'</option>';return '<select name="'+name+'"><option value="">Количество (необязательно)</option>'+opts+'</select>'}
function newTask(){modal('<h2>Создать задачу</h2><form class="form" onsubmit="createTask(event)"><input name="title" required placeholder="Например: Собрать металл"><div class="formrow">'+quantityPicker('need')+'<select name="unit"><option>Стак</option><option>Хомяк</option><option>Ящик</option></select></div><div class="formrow"><div><small class="muted">Сделать до даты</small><input name="deadline_date" class="datepick" type="date" required onclick="if(this.showPicker)this.showPicker()" onfocus="if(this.showPicker)this.showPicker()"></div><div><small class="muted">До времени</small>'+timePicker('deadline','21:00')+'</div></div><input name="place" placeholder="Куда / место"><textarea name="comment" placeholder="Комментарий"></textarea><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Создать</button></div></form>')}
async function createTask(e){e.preventDefault();let f=new FormData(e.target),need=Number(f.get('need'))||null;if(!sb||!onlineMember)return;let row={squad_id:onlineMember.squad_id,creator_id:onlineMember.id,title:f.get('title'),quantity:need,unit:f.get('unit')||'шт.',place:f.get('place')||null,priority:f.get('priority')||'Обычный',deadline:(f.get('deadline_date')+' '+getPickedTime(f,'deadline')),comment:f.get('comment')||null,status:'В процессе'};let {error}=await sb.from('tasks').insert(row);if(error){toast('Не удалось создать задачу');return}closeModal();await syncOnline();go('Задачи')}
function editTask(id){let t=db.tasks.find(x=>x.id===id);if(!t)return;let people=(db.members||[]).map(m=>m[0]),d=String(t.deadline||'').replace('T',' '),date=d.slice(0,10),time=(d.match(/(\d{2}:\d{2})/)||[])[1]||'21:00';modal('<h2>Редактировать задачу</h2><form class="form" onsubmit="saveTask(event,'+id+')"><input name="title" required value="'+esc(t.title)+'"><div class="formrow">'+quantityPicker('need',t.need||1)+'<select name="unit">'+['','Стак','Хомяк','Ящик'].map(u=>'<option value="'+esc(u)+'" '+((u||'шт.')===t.unit?'selected':'')+'>'+(u||'Единица')+'</option>').join('')+'</select></div><div class="formrow"><div><small class="muted">Сделать до даты</small><input name="deadline_date" class="datepick" type="date" required value="'+esc(date)+'" onclick="if(this.showPicker)this.showPicker()"></div><div><small class="muted">До времени</small>'+timePicker('deadline',time)+'</div></div><input name="place" value="'+esc(t.place||'')+'" placeholder="Куда / место"><select name="owner"><option value="">Ответственный (необязательно)</option>'+people.map(n=>'<option '+(n===t.owner?'selected':'')+'>'+esc(n)+'</option>').join('')+'</select><textarea name="comment" placeholder="Комментарий">'+esc(t.comment||'')+'</textarea><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveTask(e,id){e.preventDefault();let f=new FormData(e.target),owner=String(f.get('owner')||''),assignee=null;if(owner){let m=(db.members||[]).find(x=>x[0]===owner);if(m){let r=await sb.from('members').select('id').eq('squad_id',onlineMember.squad_id).eq('nick',owner).maybeSingle();if(r.data)assignee=r.data.id}}let deadline=f.get('deadline_date')+' '+getPickedTime(f,'deadline');let r=await sb.rpc('update_task_details',{p_task_id:id,p_title:f.get('title'),p_quantity:Number(f.get('need'))||null,p_unit:f.get('unit')||'шт.',p_place:f.get('place')||'',p_deadline:deadline,p_comment:f.get('comment')||'',p_assignee_id:assignee});if(r.error){toast('Редактировать может создатель или админ');return}closeModal();await syncOnline();toast('Задача обновлена')}
async function joinTask(id){let r=await sb.rpc('claim_task',{p_task_id:id});if(r.error){toast('Не удалось взять задачу');return}await syncOnline();toast('Задача взята')}
async function addContribution(id){let q=Number(prompt('Сколько добавить?'));if(!q||q<1)return;let t=db.tasks.find(x=>x.id===id);let {error}=await sb.from('task_contributions').insert({task_id:id,member_id:onlineMember.id,amount:q});if(error){toast('Не удалось добавить вклад');return}if(t&&t.need&&Number(t.done||0)+q>=Number(t.need)&&t.status!=='Выполнена'){let r=await sb.rpc('set_task_status',{p_task_id:id,p_status:'Выполнено'});if(r.error){toast('Количество собрано, но статус не изменён автоматически')}}await syncOnline();if(t&&t.need&&Number(t.done||0)+q>=Number(t.need)){showTaskComplete()}else toast('Вклад добавлен')}
function historyTask(id){let t=db.tasks.find(x=>x.id===id);modal('<h2>История · '+esc(t.title)+'</h2><div class="list">'+(t.history.length?t.history.map(h=>'<div class="item itemtop"><span>'+esc(h.nick)+' · +'+h.qty+' '+esc(t.unit)+'</span><button class="ghost" onclick="undoContribution('+id+','+h.id+')">Отменить</button></div>').join(''):'<div class="empty">Вкладов пока нет</div>')+'</div><div class="dialogfoot"><button class="ghost" onclick="closeModal()">Закрыть</button></div>')}
async function undoContribution(id,cid){let t=db.tasks.find(x=>x.id===id),h=t?.history?.find(x=>x.id===cid),after=Math.max(0,Number(t?.done||0)-Number(h?.qty||0));let {error}=await sb.from('task_contributions').delete().eq('id',cid);if(error){toast('Нельзя отменить этот вклад');return}if(t&&t.need&&after<Number(t.need)&&(t.status==='Выполнено'||t.status==='Выполнена')){let r=await sb.rpc('set_task_status',{p_task_id:id,p_status:'В процессе'});if(r.error)toast('Количество уменьшено, но статус не изменён')}closeModal();await syncOnline();toast('Вклад отменён')}
async function toggleTask(id){let t=db.tasks.find(x=>x.id===id),status=t.status==='Выполнено'||t.status==='Выполнена'?'В процессе':'Выполнено';let r=await sb.rpc('set_task_status',{p_task_id:id,p_status:status});if(r.error){toast('Изменить статус может ответственный, создатель или админ');return}await syncOnline()}
async function deleteTask(id){let t=db.tasks.find(x=>x.id===id);if(!t)return;if(!confirm('Удалить эту задачу?'))return;let {error}=await sb.from('tasks').delete().eq('id',id);if(error){toast('Удалить может только создатель или админ');return}await syncOnline();toast('Задача удалена')}
function newOp(){modal('<h2>План на рейд</h2><form class="form" onsubmit="createOp(event)"><input name="title" required placeholder="Название / цель"><input name="sector" placeholder="Сектор, например D3"><label class="photoupload"><span>Фото для рейда</span><input name="images" type="file" accept="image/*" multiple onchange="previewRaidPhotos(this)"><small class="muted">До 5 фото · максимум 5 МБ каждое</small></label><div id="raidPhotoPreview" class="raidphotopreview"></div><div class="formrow"><div><small class="muted">Дата</small><input name="raid_date" class="datepick" type="date" required onclick="if(this.showPicker)this.showPicker()" onfocus="if(this.showPicker)this.showPicker()"></div><div><small class="muted">Время</small>'+timePicker('time','20:00')+'</div></div><input name="walls" type="number" min="0" placeholder="Количество стен"><input name="loadout" placeholder="Что взять: С4, гранаты, медицина..."><input name="transport" placeholder="Транспорт"><input name="rally_point" placeholder="Точка сбора"><textarea name="note" placeholder="Подготовка / комментарий"></textarea><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Создать</button></div></form>')}
async function uploadRaidPhotos(input){let files=Array.from(input?.files||[]).slice(0,5),urls=[];for(let file of files){if(file.size>5242880)throw new Error('Фото больше 5 МБ');let ext=(file.name.split('.').pop()||'jpg').toLowerCase(),path=onlineMember.squad_id+'/'+Date.now()+'-'+Math.random().toString(36).slice(2)+'.'+ext;let r=await sb.storage.from('raid-photos').upload(path,file,{contentType:file.type||'image/jpeg'});if(r.error)throw r.error;urls.push(sb.storage.from('raid-photos').getPublicUrl(path).data.publicUrl)}return urls}
function previewRaidPhotos(input){let box=$('#raidPhotoPreview'),files=Array.from(input.files||[]).slice(0,5);if(box)box.innerHTML=files.map(f=>'<img src="'+URL.createObjectURL(f)+'" alt="Фото для рейда">').join('')}
async function createOp(e){e.preventDefault();let f=new FormData(e.target),btn=e.submitter;if(btn){btn.disabled=true;btn.textContent='Загрузка…'}let photos=[];try{photos=await uploadRaidPhotos(e.target.elements.images)}catch(x){if(btn){btn.disabled=false;btn.textContent='Создать'}toast(x.message||'Не удалось загрузить фото');return}let {error}=await sb.from('raids').insert({squad_id:onlineMember.squad_id,creator_id:onlineMember.id,title:f.get('title'),raid_time:getPickedTime(f,'time'),raid_date:f.get('raid_date'),sector:f.get('sector')||null,walls:Number(f.get('walls'))||null,loadout:f.get('loadout')||null,transport:f.get('transport')||null,rally_point:f.get('rally_point')||null,target_images:photos,note:f.get('note')||null});if(error){if(btn){btn.disabled=false;btn.textContent='Создать'}toast('Не удалось создать план');return}closeModal();await syncOnline();render()}
function editOp(id){let o=db.ops.find(x=>x.id===id);if(!o)return;modal('<h2>Редактировать план</h2><form class="form" onsubmit="saveOp(event,'+id+')"><input name="title" required value="'+esc(o.title)+'"><input name="sector" value="'+esc(o.sector||'')+'" placeholder="Сектор, например D3">'+((o.images&&o.images.length)?'<div><small class="muted">ФОТО ДЛЯ РЕЙДА</small><div class="raidphotopreview">'+o.images.map(u=>'<img src="'+esc(u)+'" alt="Фото для рейда">').join('')+'</div></div>':'')+'<label class="photoupload"><span>Добавить / заменить фото</span><input name="images" type="file" accept="image/*" multiple onchange="previewRaidPhotos(this)"><small class="muted">До 5 фото</small></label><div id="raidPhotoPreview" class="raidphotopreview"></div><div class="formrow"><div><small class="muted">Дата</small><input name="raid_date" class="datepick" type="date" required value="'+esc(o.date||'')+'" onclick="if(this.showPicker)this.showPicker()" onfocus="if(this.showPicker)this.showPicker()"></div><div><small class="muted">Время</small>'+timePicker('time',o.time||'20:00')+'</div></div><input name="walls" type="number" min="0" value="'+(o.walls||'')+'" placeholder="Количество стен"><input name="loadout" value="'+esc(o.loadout||'')+'" placeholder="Что взять"><input name="transport" value="'+esc(o.transport||'')+'" placeholder="Транспорт"><input name="rally_point" value="'+esc(o.rally_point||'')+'" placeholder="Точка сбора"><textarea name="note" placeholder="Подготовка / комментарий">'+esc(o.note)+'</textarea><div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveOp(e,id){e.preventDefault();let f=new FormData(e.target),o=db.ops.find(x=>x.id===id),photos=Array.isArray(o?.images)?o.images:[];if(e.target.elements.images?.files?.length){try{photos=await uploadRaidPhotos(e.target.elements.images)}catch(x){toast('Не удалось загрузить фото');return}}let {error}=await sb.from('raids').update({title:f.get('title'),raid_date:f.get('raid_date'),raid_time:getPickedTime(f,'time'),sector:f.get('sector')||null,walls:Number(f.get('walls'))||null,loadout:f.get('loadout')||null,transport:f.get('transport')||null,rally_point:f.get('rally_point')||null,target_images:photos,note:f.get('note')||null}).eq('id',id);if(error){toast('Редактировать может создатель или админ');return}closeModal();await syncOnline();toast('Рейд обновлён')}
async function deleteOp(id){if(!confirm('Удалить этот рейд?'))return;let {error}=await sb.from('raids').delete().eq('id',id);if(error){toast('Удалить может создатель или админ');return}await syncOnline();toast('Рейд удалён')}
async function toggleRaid(id){let o=db.ops.find(x=>x.id===id),joined=(o.participants||[]).includes(db.profile.nick);let q=joined?sb.from('raid_participants').delete().eq('raid_id',id).eq('member_id',onlineMember.id):sb.from('raid_participants').insert({raid_id:id,member_id:onlineMember.id});let {error}=await q;if(error){toast('Не удалось изменить участие');return}await syncOnline();toast(joined?'Ты вышел из рейда':'Ты записался на рейд')}
function raidPeople(o){let p=Array.isArray(o.participants)?o.participants:[];return p.length?p.map(n=>'<span class="badge work">'+esc(n)+'</span>').join(' '):'<span class="muted">Пока никто не записался</span>'}
async function setPresence(s){if(s==='Без меня')s='Не буду';let old={...db.presence};db.presence.status=s;if(s!=='Буду')db.presence.time='';save();render();let row={squad_id:onlineMember.squad_id,member_id:onlineMember.id,day:moscowPresenceDay(),status:s,join_time:s==='Буду'?(db.presence.time||null):null,updated_at:new Date().toISOString()};let {error}=await sb.from('presence_history').upsert(row,{onConflict:'member_id,day'});if(error){db.presence=old;save();render();toast('Ошибка синхронизации');return}await syncOnline();if(s==='Буду')setTime()}function setTime(){modal('<h2>Время захода</h2><form class="form" onsubmit="saveTime(event)"><label class="muted">Выбери время</label>'+timePicker('time',db.presence.time||'20:00')+'<div class="dialogfoot"><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}async function saveTime(e){e.preventDefault();let f=new FormData(e.target),t=getPickedTime(f,'time');db.presence.time=t;let status=db.presence.status==='Не буду'?'Буду':db.presence.status;let row={squad_id:onlineMember.squad_id,member_id:onlineMember.id,day:moscowPresenceDay(),status,join_time:t,updated_at:new Date().toISOString()};let {error}=await sb.from('presence_history').upsert(row,{onConflict:'member_id,day'});if(error){toast('Ошибка синхронизации');return}closeModal();await syncOnline();toast('Время обновлено')}
function editProfile(){let admin=db.profile.access==='admin';modal('<h2>Профиль бойца</h2>'+(admin?'<div style="margin-bottom:12px"><span class="badge work">АДМИНИСТРАТОР FURY</span></div>':'')+'<form class="form" onsubmit="saveProfile(event)"><input name="nick" required value="'+esc(db.profile.nick)+'" placeholder="Ник"><select name="role">'+['Rifler','Bomber','Locker','Builder','Helper','Sniper'].map(r=>'<option '+(r===db.profile.role?'selected':'')+'>'+r+'</option>').join('')+'</select><div class="dialogfoot profile-actions"><button type="button" class="logoutbtn" onclick="logoutSquad()">ВЫЙТИ</button><span class="profile-actions-spacer" style="flex:1"></span><button type="button" class="ghost" onclick="closeModal()">Отмена</button><button class="primary">Сохранить</button></div></form>')}
async function saveProfile(e){e.preventDefault();let f=new FormData(e.target);let {error}=await sb.from('members').update({nick:f.get('nick'),game_role:f.get('role')}).eq('id',onlineMember.id);if(error){toast('Не удалось сохранить профиль');return}onlineMember.nick=f.get('nick');onlineMember.game_role=f.get('role');db.profile={nick:onlineMember.nick,role:onlineMember.game_role,access:onlineMember.access_role};save();closeModal();await syncOnline();toast('Профиль сохранён')}
async function logoutSquad(){if(!confirm('Выйти из профиля на этом устройстве?'))return;if(sb)await sb.auth.signOut({scope:'local'});onlineMember=null;localStorage.removeItem(K);db=JSON.parse(JSON.stringify(base));closeModal();render();document.documentElement.classList.add('auth-lock');toast('Вы вышли');setTimeout(()=>joinOnline(),300)}
function wallWord(n){let a=Math.abs(n)%100,b=a%10;return a>10&&a<20?'СТЕН':b===1?'СТЕНА':b>=2&&b<=4?'СТЕНЫ':'СТЕН'}
async function refreshWallMetric(){if(!sb||!onlineMember)return;let r=await sb.from('explosives_inventory').select('item,quantity').eq('squad_id',onlineMember.squad_id);if(r.error)return;let dmg=0;(r.data||[]).forEach(x=>{let q=Number(x.quantity||0);if(x.item==='С4')dmg+=q*400;else if(x.item==='РПГ')dmg+=q*200;else if(x.item==='ГРАНАТА'||x.item==='Граната')dmg+=q*100;else if(x.item==='ДИНАМИТ')dmg+=q*200});window.furyWalls=Math.floor(dmg/1200);let el=$('#wallMetric');if(el)el.textContent=window.furyWalls+' '+wallWord(window.furyWalls);let total=$('#explosiveWallsTotal');if(total)total.textContent=window.furyWalls+' '+wallWord(window.furyWalls)}
function stats(){loadExplosives()}
async function loadExplosives(){
 $('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>Взрыв</h2><span class="muted">Общий склад отряда. Любой участник может изменить количество.</span></div></div><div id="explosivesBody"><div class="empty">Загрузка…</div></div></div>';
 let b=$('#explosivesBody');if(!sb||!onlineMember){b.innerHTML='<div class="empty">Войди в состав, чтобы видеть склад</div>';return}
 let {data,error}=await sb.from('explosives_inventory').select('item,quantity,updated_at').eq('squad_id',onlineMember.squad_id);
 if(error){b.innerHTML='<div class="empty">Не удалось загрузить склад</div>';return}
 const order=['С4','РПГ','ГРАНАТА','ДИНАМИТ','ПАЙПА','40'],map={};(data||[]).forEach(x=>map[x.item==='Граната'?'ГРАНАТА':x.item]=x);
 b.innerHTML='<div class="explosivegrid">'+order.map(item=>{let x=map[item]||{quantity:0},q=Number(x.quantity||0),perWall={['С4']:3,['РПГ']:6,['ГРАНАТА']:12,['ДИНАМИТ']:6}[item],itemWalls=perWall?Math.floor(q/perWall):0,toNext=perWall?q%perWall:0;return '<div class="explosiveitem"><div><h3>'+esc(item)+'</h3><span class="muted">В наличии'+(perWall?' · <b class="itemwalls">'+itemWalls+' '+wallWord(itemWalls).toLowerCase()+(toNext?' + '+toNext+' '+(item==='С4'?'C4':item==='РПГ'?'РПГ':item==='ГРАНАТА'?(toNext===1?'граната':toNext>=2&&toNext<=4?'гранаты':'гранат'):'динамит'):'')+'</b>':'')+'</span></div><div class="explosiveedit"><button type="button" onclick="changeExplosive(\''+(item==='ГРАНАТА'?'Граната':item)+'\',-1)">−</button><input type="number" min="0" data-item="'+esc(item==='ГРАНАТА'?'Граната':item)+'" value="'+Number(x.quantity||0)+'" onchange="setExplosive(\''+(item==='ГРАНАТА'?'Граната':item)+'\',this.value)"><button type="button" onclick="changeExplosive(\''+(item==='ГРАНАТА'?'Граната':item)+'\',1)">+</button></div></div>'}).join('')+'</div><div class="explosivewalls"><span>МОЖНО ВЗОРВАТЬ</span><b id="explosiveWallsTotal">0 СТЕН</b></div>';
 refreshWallMetric();
}
function explosiveInput(item){return document.querySelector('.explosiveedit input[data-item="'+CSS.escape(item)+'"]')}
function updateExplosiveInput(item,q){let el=explosiveInput(item);if(el&&document.activeElement!==el)el.value=Number(q||0)}
async function setExplosive(item,value){
 let q=Math.max(0,parseInt(value,10)||0),el=explosiveInput(item);if(el)el.value=q;
 let {error}=await sb.from('explosives_inventory').update({quantity:q,updated_at:new Date().toISOString(),updated_by:onlineMember.id}).eq('squad_id',onlineMember.squad_id).eq('item',item);
 if(error){toast('Не удалось изменить количество');return}
 await refreshWallMetric()
}
async function changeExplosive(item,delta){
 let el=explosiveInput(item),current=Math.max(0,parseInt(el?.value,10)||0),next=Math.max(0,current+delta);if(el)el.value=next;await setExplosive(item,next)
}

async function renderHomePlace(){
 const body=$('#homePlaceBody');if(!body||!sb||!onlineMember)return;
 let r;try{r=await sb.rpc('get_squad_place_posts',{p_kind:'home'})}catch(e){r={error:e}}
 if(!$('#homePlaceBody'))return;
 if(r.error){body.innerHTML='<div class="empty">Не удалось загрузить публикации</div>';return}
 let d=placeDraft.home||{images:[],comment:''},allData=r.data||[],data=homeFeedAll?allData.slice(0,homeFeedShown):allData.slice(0,5);
 body.innerHTML='<div class="place-compose"><div class="raidphotos placephotos">'+d.images.map((u,i)=>'<div class="placephoto"><img src="'+esc(u)+'" onclick="openRaidPhoto(\''+esc(u)+'\')" style="cursor:zoom-in"><button class="place-photo-remove" onclick="removeDraftPlacePhoto(\'home\','+i+')">×</button></div>').join('')+'</div><input id="placePhotoFile" type="file" accept="image/*" multiple><div class="muted" style="margin:8px 0 14px">Ctrl+V — вставить скриншот из буфера · либо выбрать файлы выше. Максимум 5 фото.</div><textarea id="placeComment" class="place-comment" placeholder="Напишите комментарий к публикации…">'+esc(d.comment||'')+'</textarea><button class="primary" style="margin-top:12px;width:100%" onclick="publishPlacePost(\'home\')">ОПУБЛИКОВАТЬ</button></div><div class="list" style="margin-top:18px">'+(data.length?data.map(p=>'<div class="item"><div class="itemtop"><b>'+esc(p.author_nick||'Участник')+'</b><span class="muted">'+new Date(p.created_at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})+'</span></div><div class="raidphotos placephotos">'+(p.images||[]).map(u=>'<div class="placephoto"><img src="'+esc(u)+'" onclick="openRaidPhoto(\''+esc(u)+'\')" style="cursor:zoom-in"></div>').join('')+'</div>'+(p.comment?'<div style="margin-top:12px">'+esc(p.comment)+'</div>':'')+'<div class="actions"><button onclick="editPlacePost('+p.id+',\'home\')">Редактировать</button>'+((p.created_by===onlineMember.id||onlineMember.access_role==='admin'||db.profile?.access==='admin')?'<button class="danger" onclick="deletePlacePost('+p.id+',\'home\')">Удалить публикацию</button>':'')+'</div></div>').join(''):'<div class="empty">Публикаций пока нет</div>')+'</div>';
 $('#placePhotoFile')?.addEventListener('change',e=>uploadPlaceFiles('home',[...e.target.files]));
 $('#placeComment')?.addEventListener('input',e=>{placeDraft.home=placeDraft.home||{images:[],comment:''};placeDraft.home.comment=e.target.value});
 let total=allData.length;
 if(total>(homeFeedAll?homeFeedShown:5)){let b=document.createElement('button');b.className='ghost';b.style.cssText='width:100%;margin-top:12px';b.textContent=homeFeedAll?'ПОКАЗАТЬ ЕЩЁ 10':'ПОКАЗАТЬ ВСЕ ПУБЛИКАЦИИ';b.onclick=()=>{if(homeFeedAll)homeFeedShown+=10;else{homeFeedAll=true;homeFeedShown=10}renderHomePlace()};body.appendChild(b)}
}
function placeTitle(kind){return kind==='stash'?'Схрон':'Базы'}
let homeFeedAll=false,homeFeedShown=10;
let placeDraft={stash:{images:[],comment:''},base:{images:[],comment:''},home:{images:[],comment:''}},placeEdit=null;
function refreshPlaceKind(kind){if(kind==='home'){if(page==='Главная'||page==='Сегодня')renderHomePlace();return}placePage(kind)}
async function placePage(kind){
 let title=placeTitle(kind);
 $('#view').innerHTML='<div class="card"><div class="toolbar"><div><h2>'+title+'</h2><span class="muted">Фото и комментарии сохраняются отдельными публикациями.</span></div></div><div id="placeBody"><div class="empty">Загрузка…</div></div></div>';
 let body=$('#placeBody');
 if(!sb){if(body)body.innerHTML='<div class="empty">Ошибка подключения Supabase</div>';return}
 if(!onlineMember){if(body)body.innerHTML='<div class="empty">Профиль подключается…</div>';setTimeout(()=>{if(page===title&&onlineMember)placePage(kind)},600);return}
 let data=null,error=null;
 try{let r=await Promise.race([sb.rpc('get_squad_place_posts',{p_kind:kind}),new Promise((_,rej)=>setTimeout(()=>rej(new Error('timeout')),8000))]);data=r.data;error=r.error}catch(e){error=e}
 if(error){console.error('placePage',kind,error);if(body)body.innerHTML='<div class="empty">Ошибка загрузки: '+esc(error.message||String(error))+'<br><button class="ghost" style="margin-top:12px" onclick="placePage(\''+kind+'\')">Повторить</button></div>';return}
 if(error){$('#placeBody').innerHTML='<div class="empty">Не удалось загрузить</div>';return}
 let d=placeDraft[kind]||{images:[],comment:''};
 $('#placeBody').innerHTML='<div class="place-compose"><div class="raidphotos placephotos">'+d.images.map((u,i)=>'<div class="placephoto"><img src="'+esc(u)+'" onclick="openRaidPhoto(\''+esc(u)+'\')" style="cursor:zoom-in"><button class="place-photo-remove" title="Удалить фото" aria-label="Удалить фото" onclick="removeDraftPlacePhoto(\''+kind+'\','+i+')">×</button></div>').join('')+'</div><input id="placePhotoFile" type="file" accept="image/*" multiple><div class="muted" style="margin:8px 0 14px">Ctrl+V — вставить скриншот из буфера · либо выбрать файлы выше. Максимум 5 фото.</div><textarea id="placeComment" class="place-comment" placeholder="Напишите комментарий к публикации…">'+esc(d.comment||'')+'</textarea><button class="primary" style="margin-top:12px;width:100%" onclick="publishPlacePost(\''+kind+'\')">ОПУБЛИКОВАТЬ</button></div><div class="list" style="margin-top:18px">'+((data||[]).length?(data||[]).map(p=>'<div class="item"><div class="itemtop"><b>'+esc(p.author_nick||'Участник')+'</b><span class="muted">'+new Date(p.created_at).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'})+'</span></div><div class="raidphotos placephotos">'+(p.images||[]).map(u=>'<div class="placephoto"><img src="'+esc(u)+'" onclick="openRaidPhoto(\''+esc(u)+'\')" style="cursor:zoom-in"></div>').join('')+'</div>'+(p.comment?'<div style="margin-top:12px">'+esc(p.comment)+'</div>':'')+'<div class="actions"><button onclick="editPlacePost('+p.id+',\''+kind+'\')">Редактировать</button>'+((p.created_by===onlineMember.id||onlineMember.access_role==='admin'||db.profile?.access==='admin')?'<button class="danger" onclick="deletePlacePost('+p.id+',\''+kind+'\')">Удалить публикацию</button>':'')+'</div>'+'</div>').join(''):'<div class="empty">Публикаций пока нет</div>')+'</div>';
 $('#placePhotoFile')?.addEventListener('change',e=>uploadPlaceFiles(kind,[...e.target.files]));
 $('#placeComment')?.addEventListener('input',e=>{placeDraft[kind]=placeDraft[kind]||{images:[],comment:''};placeDraft[kind].comment=e.target.value});
}
async function uploadPlaceFiles(kind,files){let commentEl=$('#placeComment');if(commentEl){placeDraft[kind]=placeDraft[kind]||{images:[],comment:''};placeDraft[kind].comment=commentEl.value}files=[...(files||[])].filter(f=>f&&f.type&&f.type.startsWith('image/'));if(!files.length){toast('В буфере нет изображения');return}let d=placeDraft[kind]||{images:[],comment:''},slots=5-d.images.length;if(slots<=0){toast('Максимум 5 фото');return}for(let file of files.slice(0,slots)){if(file.size>10*1024*1024){toast('Фото больше 10 МБ пропущено');continue}let ext=(file.name?.split('.').pop()||file.type.split('/')[1]||'png').replace(/[^a-zA-Z0-9]/g,'').toLowerCase(),path=onlineMember.squad_id+'/'+kind+'/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.'+ext;let up=await sb.storage.from('squad-photos').upload(path,file,{contentType:file.type,upsert:false});if(up.error){toast('Не удалось загрузить фото');continue}d.images.push(sb.storage.from('squad-photos').getPublicUrl(path).data.publicUrl)}placeDraft[kind]=d;refreshPlaceKind(kind)}
function removeDraftPlacePhoto(kind,i){let commentEl=$('#placeComment');if(commentEl){placeDraft[kind]=placeDraft[kind]||{images:[],comment:''};placeDraft[kind].comment=commentEl.value}let d=placeDraft[kind];if(!d)return;d.images.splice(i,1);refreshPlaceKind(kind)}
async function publishPlacePost(kind){let d=placeDraft[kind]||{images:[]},comment=$('#placeComment')?.value.trim()||'';if(!d.images.length&&!comment){toast('Добавь фото или комментарий');return}let {error}=await sb.from('squad_place_posts').insert({squad_id:onlineMember.squad_id,kind,images:d.images.slice(0,5),comment,created_by:onlineMember.id});if(error){toast('Не удалось опубликовать');return}placeDraft[kind]={images:[],comment:''};toast('Опубликовано');refreshPlaceKind(kind)}
async function editPlacePost(id,kind){let {data:p,error}=await sb.from('squad_place_posts').select('*').eq('id',id).single();if(error||!p){toast('Редактирование недоступно');return}placeEdit={id:p.id,kind,images:[...(p.images||[])],comment:p.comment||''};openPlaceEditModal()}
function cancelPlaceEdit(){placeEdit=null;closeModal()}
function openPlaceEditModal(){let p=placeEdit;if(!p)return;modal('<h2>Редактировать публикацию</h2><div class="raidphotos placephotos">'+p.images.map((u,i)=>'<div class="placephoto"><img src="'+esc(u)+'" onclick="openRaidPhoto(\''+esc(u)+'\')" style="cursor:zoom-in"><button class="place-photo-remove" onclick="removePlaceEditPhoto('+i+')">×</button></div>').join('')+'</div><input id="placeEditFiles" type="file" accept="image/*" multiple><div class="muted" style="margin:8px 0 14px">Можно добавить фото. Максимум 5.</div><textarea id="placeEditComment" class="place-comment" placeholder="Комментарий">'+esc(p.comment)+'</textarea><div class="dialogfoot"><button class="ghost" onclick="cancelPlaceEdit()">Отмена</button><button class="primary" onclick="savePlaceEdit()">Сохранить</button></div>');$('#placeEditFiles')?.addEventListener('change',e=>uploadPlaceEditFiles([...e.target.files]))}
function removePlaceEditPhoto(i){if(!placeEdit)return;placeEdit.comment=$('#placeEditComment')?.value??placeEdit.comment;placeEdit.images.splice(i,1);openPlaceEditModal()}
async function uploadPlaceEditFiles(files){if(!placeEdit)return;placeEdit.comment=$('#placeEditComment')?.value??placeEdit.comment;files=[...(files||[])].filter(f=>f?.type?.startsWith('image/')).slice(0,5-placeEdit.images.length);for(let file of files){if(file.size>10*1024*1024){toast('Фото больше 10 МБ пропущено');continue}let ext=(file.name?.split('.').pop()||file.type.split('/')[1]||'png').replace(/[^a-zA-Z0-9]/g,'').toLowerCase(),path=onlineMember.squad_id+'/'+placeEdit.kind+'/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.'+ext;let up=await sb.storage.from('squad-photos').upload(path,file,{contentType:file.type,upsert:false});if(up.error){toast('Не удалось загрузить фото');continue}placeEdit.images.push(sb.storage.from('squad-photos').getPublicUrl(path).data.publicUrl)}openPlaceEditModal()}
async function savePlaceEdit(){if(!placeEdit)return;placeEdit.comment=$('#placeEditComment')?.value.trim()||'';let {error}=await sb.from('squad_place_posts').update({images:placeEdit.images.slice(0,5),comment:placeEdit.comment}).eq('id',placeEdit.id);if(error){toast('Не удалось сохранить');return}let kind=placeEdit.kind;placeEdit=null;closeModal();toast('Публикация обновлена');placePage(kind)}
async function deletePlacePost(id,kind){if(!confirm('Удалить публикацию?'))return;let {error}=await sb.from('squad_place_posts').delete().eq('id',id);if(error){toast('Не удалось удалить');return}refreshPlaceKind(kind)}
function authScreen(){modal('<h2>Вход в FURY</h2><div id="authForm"></div>');showMemberLogin()}
function showMemberLogin(){let a=$('#authForm');if(!a)return;a.innerHTML='<form class="form" onsubmit="doJoin(event)"><input name="code" required placeholder="Код состава"><input name="nick" required value="" autocomplete="off" placeholder="Ник"><select name="role" required><option value="" selected disabled>Выбрать роль</option>'+['Rifler','Bomber','Locker','Builder','Helper','Sniper'].map(r=>'<option value="'+r+'">'+r+'</option>').join('')+'</select><button class="primary">ВОЙТИ В СОСТАВ</button></form>'}
function showAdminLogin(){let a=$('#authForm');if(!a)return;$('#adminTab')?.classList.add('on');$('#memberTab')?.classList.remove('on');a.innerHTML='<form class="form" onsubmit="adminLogin(event)"><input name="email" type="email" required autocomplete="username" placeholder="E-mail"><input name="password" type="password" required minlength="6" autocomplete="current-password" placeholder="Пароль"><button class="primary">ВОЙТИ КАК АДМИН</button><button type="button" class="ghost" onclick="adminSignup(event)">ПЕРВЫЙ ВХОД / СОЗДАТЬ ПАРОЛЬ</button><div id="adminAuthStatus" class="muted" style="min-height:18px"></div></form><small class="muted">При первом входе создай пароль. После этого используй обычный вход администратора.</small>'}
async function adminSignup(e){if(e)e.preventDefault();let st=$('#adminAuthStatus'),form=$('#authForm form');if(!form)return;let f=new FormData(form),email=String(f.get('email')||'').trim(),password=String(f.get('password')||'');if(!email){if(st)st.textContent='Введи e-mail';return}if(password.length<6){if(st)st.textContent='Пароль минимум 6 символов';return}if(st)st.textContent='Создаю учётную запись…';let r=await sb.auth.signUp({email,password});if(r.error){if(st)st.textContent='Ошибка: '+r.error.message;return}if(!r.data.session){if(st)st.textContent='Готово. Проверь почту и подтверди e-mail, затем нажми «ВОЙТИ КАК АДМИН».';return}if(st)st.textContent='Учётная запись создана. Вхожу…';await finishAdminLogin()}
async function adminLogin(e){e.preventDefault();let f=new FormData(e.target);await sb.auth.signOut({scope:'local'});let r=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(r.error){toast('Неверный e-mail или пароль');return}await finishAdminLogin()}
async function finishAdminLogin(){let r=await sb.rpc('claim_admin_account');if(r.error){toast('Эта учётка не является администратором');await sb.auth.signOut({scope:'local'});return}onlineMember=r.data;db.profile={nick:r.data.nick,role:r.data.game_role,access:r.data.access_role};save();closeModal();await syncOnline();unlockApp();toast('Вход администратора выполнен')}
async function joinOnline(){if(!sb)return;let {data:{session}}=await sb.auth.getSession();if(session){let {data:m}=await sb.rpc('current_member');if(m){onlineMember=m;db.profile={nick:m.nick,role:m.game_role,access:m.access_role};save();await syncOnline();unlockApp();return}if(!session.user.is_anonymous&&session.user.email?.toLowerCase()==='nikitinrf@bk.ru'){await finishAdminLogin();return}}authScreen()}
async function ensureAnonymous(){let {data:{session}}=await sb.auth.getSession();if(!session||!session.user.is_anonymous){if(session)await sb.auth.signOut({scope:'local'});let r=await sb.auth.signInAnonymously();if(r.error)throw r.error}}
async function doJoin(e){e.preventDefault();let f=new FormData(e.target),nick=String(f.get('nick')||'').trim(),code=String(f.get('code')||'').trim();try{await ensureAnonymous()}catch(x){toast('Не удалось создать сессию');return}if(nick.toLowerCase()==='k1t0'){let r=await sb.rpc('join_admin_device',{p_code:code,p_nick:nick});if(r.error){toast('Неверный код администратора');return}onlineMember=r.data;db.profile={nick:r.data.nick,role:r.data.game_role,access:'admin'};save();closeModal();await syncOnline();unlockApp();toast('Вход администратора выполнен');return}let {data,error}=await sb.rpc('join_squad',{p_code:code,p_nick:nick,p_role:f.get('role')});if(error){toast(error.message.includes('duplicate')?'Ник уже занят':'Неверный код или ошибка входа');return}onlineMember=data;db.profile={nick:data.nick,role:data.game_role,access:data.access_role};save();closeModal();await syncOnline();unlockApp();toast('Добро пожаловать в FURY')}

function showK1t0Login(code){let a=$('#authForm');if(!a)return;a.innerHTML='<div class="form"><div class="muted">Профиль <b class="acid">k1t0</b></div><div class="muted">Вход без пароля через ссылку на почте.</div><button class="primary" onclick="sendK1t0MagicLink(\''+esc(code||'').replace(/'/g,"\\'")+'\')">ПОЛУЧИТЬ ССЫЛКУ НА ПОЧТУ</button><button type="button" class="ghost" onclick="showMemberLogin()">Назад</button><div id="k1t0AuthStatus" class="muted" style="min-height:18px"></div></div>'}
async function sendK1t0MagicLink(code){let st=$('#k1t0AuthStatus');if(st)st.textContent='Отправляю ссылку…';if(String(code||'').trim().toUpperCase()!=='FURYHUB'){if(st)st.textContent='Неверный код состава';return}await sb.auth.signOut({scope:'local'});let redirect=location.origin+location.pathname;let r=await sb.auth.signInWithOtp({email:'nikitinrf@bk.ru',options:{shouldCreateUser:false,emailRedirectTo:redirect}});if(r.error){if(st)st.textContent='Не удалось отправить ссылку';return}if(st)st.innerHTML='Ссылка отправлена на почту.<br>Открой письмо и нажми <b>Sign in</b>.'}

let syncTimer=null;function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>{if(onlineMember&&document.visibilityState==='visible'&&page!=='Взрыв')syncOnline()},700)}
function startSharedSync(){if(window.sharedSyncStarted)return;window.sharedSyncStarted=true;setInterval(async()=>{if(onlineMember&&document.visibilityState==='visible'&&page!=='Взрыв'){window.furySilentSync=true;try{await syncOnline();await refreshWallMetric()}finally{window.furySilentSync=false}}},30000);try{sb.channel('squad-shared').on('postgres_changes',{event:'*',schema:'public'},scheduleSync).subscribe();sb.channel('explosives-live').on('postgres_changes',{event:'UPDATE',schema:'public',table:'explosives_inventory'},p=>{if(page==='Взрыв'&&p.new?.squad_id===onlineMember?.squad_id)updateExplosiveInput(p.new.item,p.new.quantity)}).subscribe()}catch(e){console.warn(e)}}
function moscowPresenceDay(){let parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hourCycle:'h23'}).formatToParts(new Date());let v=Object.fromEntries(parts.map(x=>[x.type,x.value]));let d=new Date(Date.UTC(+v.year,+v.month-1,+v.day));if(+v.hour<5)d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10)}
let protectCountdownTimer=null;
function protectClock(d){return d.toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'})}
function protectHomeHtml(p){
 let updated=new Date(p.time),starts=new Date(updated.getTime()+60*60*1000),ends=new Date(starts.getTime()+8*60*60*1000),now=new Date(),status='';
 if(now<starts){let ms=starts-now,h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);status='<div class="protect-countdown" data-start="'+starts.toISOString()+'">До начала: <b>'+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'</b></div>'}
 else if(now<ends){status='<div class="protect-active">ПРОТЕКТ АКТИВЕН</div>'}
 else{status='<div class="protect-ended">ПРОТЕКТ СПАЛ</div>'}
 setTimeout(startProtectCountdown,0);
 return '<div class="protect-who"><b>'+esc(p.nick)+'</b> · '+protectClock(updated)+'</div><div class="protect-times">Начало: <b>'+protectClock(starts)+'</b> · Спадёт: <b>'+protectClock(ends)+'</b></div>'+status;
}
function startProtectCountdown(){
 clearInterval(protectCountdownTimer);
 let el=document.querySelector('.protect-countdown[data-start]');if(!el)return;
 protectCountdownTimer=setInterval(()=>{let x=document.querySelector('.protect-countdown[data-start]');if(!x){clearInterval(protectCountdownTimer);return}let end=new Date(x.dataset.start),ms=end-new Date();if(ms<=0){clearInterval(protectCountdownTimer);if(page==='Главная')render();return}let h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000),s=Math.floor(ms%60000/1000);x.innerHTML='До начала: <b>'+String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')+'</b>'},1000);
}
async function quickProtect(){
 if(!onlineMember){toast('Профиль не найден');return}
 let {error}=await sb.from('protect_updates').insert({squad_id:onlineMember.squad_id,member_id:onlineMember.id});
 if(error){toast('Не удалось обновить протект');return}
 await syncOnline();toast('Протект обновлён')
}
function showProtectHistory(){
 let hs=db.protectHistory||[];
 let rows=hs.length?hs.map(x=>'<div class="item protect-history-item"><div><b>'+esc(x.nick)+'</b><div class="muted">'+new Date(x.time).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})+'</div></div><button class="danger protect-delete-btn" onclick="deleteProtectAt(\''+x.time+'\')">Удалить</button></div>').join(''):'<div class="empty">История пока пустая</div>';
 modal('<h2>История протекта</h2><div class="list protect-history-list">'+rows+'</div><div class="modalactions"><button class="protect-close-btn" onclick="closeModal()">Закрыть</button></div>')
}
async function deleteProtectAt(time){
 if(!confirm('Удалить эту отметку об обновлении протекта?'))return;
 let {error}=await sb.from('protect_updates').delete().eq('squad_id',onlineMember.squad_id).eq('updated_at',time);
 if(error){toast('Не удалось удалить');return}
 await syncOnline();showProtectHistory();toast('Отметка удалена')
}
function protect(){let opts=(db.members||[]).map(m=>'<option value="'+esc(m[0])+'">'+esc(m[0])+'</option>').join('');let last=db.protect?('<div class="item"><div class="muted">ПОСЛЕДНЕЕ ОБНОВЛЕНИЕ</div><h3>'+esc(db.protect.nick)+'</h3><div>'+new Date(db.protect.time).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})+'</div><div class="actions"><button class="danger" onclick="deleteProtect()">Удалить</button></div></div>'):'<div class="empty">Протект ещё не обновляли</div>';$('#view').innerHTML='<div class="card"><h2>Протект</h2><p class="muted">Выберите участника, который обновил протект.</p><form class="protectquick" onsubmit="saveProtect(event)"><select name="nick" required>'+opts+'</select><button class="primary protectbtn">ОБНОВИЛ ПРОТЕКТ</button></form><div style="margin-top:18px">'+last+'</div></div>'}
async function deleteProtect(){if(!db.protect)return;if(!confirm('Удалить отметку об обновлении протекта?'))return;let {error}=await sb.from('protect_updates').delete().eq('squad_id',onlineMember.squad_id).eq('updated_at',db.protect.time);if(error){toast('Не удалось удалить');return}await syncOnline();toast('Отметка удалена')}
async function saveProtect(e){e.preventDefault();let f=new FormData(e.target),nick=f.get('nick'),res=await sb.from('members').select('id').eq('squad_id',onlineMember.squad_id).eq('nick',nick).single(),member=res.data;if(!member){toast('Участник не найден');return}let {error}=await sb.from('protect_updates').insert({squad_id:onlineMember.squad_id,member_id:member.id});if(error){toast('Не удалось обновить протект');return}await syncOnline();toast('Протект обновлён')}
async function syncOnline(){if(!sb||!onlineMember)return;let day=moscowPresenceDay();let [mr,pr,tr,cr,rr,rpr,por]=await Promise.all([
sb.from('members').select('*').order('joined_at'),
sb.from('presence_history').select('*').eq('day',day),
sb.from('tasks').select('*').eq('squad_id',onlineMember.squad_id).order('created_at',{ascending:false}),
sb.from('task_contributions').select('*').order('created_at'),
sb.from('raids').select('*').eq('squad_id',onlineMember.squad_id).order('created_at',{ascending:false}),
sb.from('raid_participants').select('*'),
sb.from('protect_updates').select('*').eq('squad_id',onlineMember.squad_id).order('updated_at',{ascending:false})
]);if(mr.error||pr.error||tr.error||cr.error||rr.error||rpr.error||por.error){toast('Ошибка синхронизации');return}let ms=mr.data||[],ph=pr.data||[],nameById=Object.fromEntries(ms.map(m=>[m.id,m.nick]));db.members=ms.map(m=>{let p=ph.find(x=>x.member_id===m.id);return[m.nick,m.game_role,p?.join_time?.slice(0,5)||'',p?.status||'Не буду']});db.tasks=(tr.data||[]).map(t=>{let hs=(cr.data||[]).filter(c=>c.task_id===t.id).map(c=>({id:c.id,nick:nameById[c.member_id]||'Боец',qty:c.amount}));let done=hs.reduce((n,h)=>n+h.qty,0);return{id:t.id,title:t.title,need:t.quantity||0,done,unit:t.unit||'шт.',place:t.place||'',priority:t.priority,deadline:t.deadline||'',owner:nameById[t.assignee_id]||'',comment:t.comment||'',status:t.status,creator:nameById[t.creator_id]||'',history:hs}});db.ops=(rr.data||[]).map(r=>({id:r.id,title:r.title,date:r.raid_date||'',time:r.raid_time?.slice(0,5)||'20:00',note:r.note||'',sector:r.sector||'',walls:r.walls||0,loadout:r.loadout||'',transport:r.transport||'',rally_point:r.rally_point||'',images:r.target_images||[],creator:nameById[r.creator_id]||'',participants:(rpr.data||[]).filter(x=>x.raid_id===r.id).map(x=>nameById[x.member_id]).filter(Boolean)})).sort((a,b)=>{let av=a.date?(a.date+'T'+(a.time||'00:00')):'9999-12-31T23:59',bv=b.date?(b.date+'T'+(b.time||'00:00')):'9999-12-31T23:59';return av.localeCompare(bv)});db.protectHistory=(por.data||[]).map(x=>({member_id:x.member_id,nick:nameById[x.member_id]||'—',time:x.updated_at}));db.protect=db.protectHistory[0]||null;let me=ms.find(x=>x.id===onlineMember.id);if(me){onlineMember=me;db.profile={nick:me.nick,role:me.game_role,access:me.access_role}}let p=ph.find(x=>x.member_id===onlineMember.id);db.presence=p?{status:p.status,time:p.join_time?.slice(0,5)||''}:{status:'Не буду',time:''};save();if(!window.furySilentSync)render();startSharedSync()}
async function bootOnline(){try{sb=supabase.createClient(SUPA_URL,SUPA_KEY);await joinOnline()}catch(e){console.error(e);toast('Supabase недоступен')}}
$('#pageTitle').textContent=page;nav();render();bootOnline();

document.addEventListener('paste',async e=>{if(page!=='Схрон'&&page!=='Базы')return;let files=[...(e.clipboardData?.items||[])].filter(x=>x.kind==='file'&&x.type.startsWith('image/')).map(x=>x.getAsFile()).filter(Boolean);if(!files.length)return;e.preventDefault();if(placeEdit){await uploadPlaceEditFiles(files)}else{await uploadPlaceFiles(page==='Схрон'?'stash':'base',files)}});
